import type { KpiDefinition } from "./contracts";

/**
 * Registre des KPI (section 16.3 du plan de refonte).
 *
 * « Un KPI sans utilité explicite ou sans formule documentée n'entre pas dans ce registre. »
 * Chaque entrée porte donc sa question, sa formule, ses données requises, et le comportement
 * exact face à un `null`, à un zéro DÉCLARÉ, à une devise étrangère et à une période
 * partielle. Ce sont ces quatre comportements, pas la formule, qui font la différence entre
 * un chiffre juste et un chiffre plausible.
 *
 * La `formula` NOMME la fonction de moteur qui produit la valeur, au lieu de la paraphraser.
 * Une paraphrase serait une seconde définition, et elle divergerait au premier changement de
 * moteur sans que rien ne le signale. Quand le plan de refonte énonce lui-même une
 * convention (« EGI = loyer contractuel − vacance/pertes + autres revenus », « NOI exclut
 * principal, intérêts, impôt sur le revenu et capex »), elle est transcrite mot pour mot.
 *
 * Le registre ne contient QUE les KPI essentiels des quatorze pages des sections 20 à 33 et
 * ceux que leurs objectifs débloquent. Un catalogue exhaustif inventerait des indicateurs
 * dont aucune page n'a l'usage, ce que la section 14 interdit explicitement : « ne pas créer
 * de nouveaux KPI tant que la tâche utilisateur associée n'est pas définie ».
 */

const OBSERVED_BALANCES = "Solde de compte observé et daté";
const OBSERVED_VALUATIONS = "Valorisation de position observée et datée";
const LEDGER = "Ledger de transactions sur période déclarée couverte";
const CONTRACT = "Contrat ou échéancier de prêt";
const FX = "Taux de change à la date économique";

function definitions(entries: readonly KpiDefinition[]): Readonly<Record<string, KpiDefinition>> {
  const map: Record<string, KpiDefinition> = {};
  for (const entry of entries) map[entry.id] = entry;
  return map;
}

export const KPI_REGISTRY = definitions([
  // ─── Bilan canonique ────────────────────────────────────────────────────────────────
  {
    id: "net_worth",
    label: "Patrimoine net",
    question: "Combien est-ce que je possède réellement ?",
    formula: "grossAssets − totalLiabilities, agrégats du bilan canonique",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().structure.netWorth",
    conventions: [
      "Un compte bancaire négatif devient un passif de découvert : il ne réduit pas les actifs bruts.",
      "Les positions expliquent la composition d’une enveloppe, elles ne s’y ajoutent pas.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: [OBSERVED_BALANCES, "Encours de dette observé et daté"],
    requiredData: ["Solde ou valorisation de chaque ligne détenue", "Encours de chaque dette"],
    optionalData: ["Quote-part détenue", "Taux de change de la date de valorisation"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Ce que vous possédez, moins ce que vous devez, à la date d’arrêté. Une ligne dont la valeur manque rend le total non calculable plutôt que de l’amputer en silence.",
    technicalDetail:
      "Somme des contributions du bilan canonique. Les contributions immobilières et Business Equity y entrent par leur domaine, jamais deux fois.",
    visualisation: "VALUE_WITH_DELTA",
    pinnable: true,
    hideable: false,
  },
  {
    id: "gross_assets",
    label: "Actifs bruts",
    question: "Combien vaut ce que je détiens, avant dettes ?",
    formula: "Somme des contributions d’actif du bilan canonique",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().structure.grossAssets",
    conventions: ["Un découvert n’est pas un actif négatif : il est porté au passif."],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: [OBSERVED_BALANCES, OBSERVED_VALUATIONS],
    requiredData: ["Solde ou valorisation de chaque ligne détenue"],
    optionalData: [FX],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation: "La valeur de tout ce que vous détenez, sans retirer vos dettes.",
    technicalDetail: "Agrégat `structure.grossAssets`, avec ses réserves de calculabilité.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: true,
  },
  {
    id: "total_liabilities",
    label: "Total des dettes",
    question: "Combien dois-je au total ?",
    formula: "Somme des encours de dette et des découverts de compte",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().structure.totalLiabilities",
    conventions: [
      "La dette d’une société détenue réduit son Equity Value et n’entre jamais au passif personnel.",
      "Aucune ligne de passif immobilier n’est produite par le domaine immobilier : elle doublerait celle des dettes.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: ["Encours de dette observé et daté", OBSERVED_BALANCES],
    requiredData: ["Encours de chaque dette"],
    optionalData: [FX],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation: "Ce que vous devez, dettes bancaires et découverts compris.",
    technicalDetail: "Agrégat `structure.totalLiabilities`.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "immediate_cash",
    label: "Liquidité immédiate",
    question: "Combien est disponible maintenant ?",
    formula: "Somme des soldes de comptes à liquidité immédiate",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().structure.immediateCash",
    conventions: [
      "LIQUIDITÉ ≠ PATRIMOINE NET.",
      "Le cash logé dans un PEA ou un CTO est un cash d’enveloppe : il est exclu du cash immédiat.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: [OBSERVED_BALANCES],
    requiredData: ["Solde observé de chaque compte à liquidité immédiate"],
    optionalData: [FX],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "OBSERVED",
    userExplanation:
      "L’argent mobilisable tout de suite. Le cash d’un compte-titres n’en fait pas partie : il est dans une enveloppe.",
    technicalDetail: "Agrégat `structure.immediateCash`, distinct de `investmentCash`.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: false,
  },
  {
    id: "asset_allocation",
    label: "Répartition du patrimoine",
    question: "Comment mon patrimoine est-il composé ?",
    formula: "Parts de liquide, financier, immobilier, entreprise et autres dans les actifs bruts",
    engine: "balance-sheet-view.canonicalAllocation",
    conventions: [
      "Une enveloppe dont la composition dépasse sa valeur comptable ne reçoit aucune exposition de marché.",
      "Chaque tranche est exprimée en devise de reporting après conversion datée.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: [OBSERVED_BALANCES, OBSERVED_VALUATIONS],
    requiredData: ["Classement de liquidité de chaque compte", "Valorisation de chaque ligne"],
    optionalData: ["Positions détaillées par enveloppe", FX],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation: "La part de chaque grande famille d’actifs dans ce que vous détenez.",
    technicalDetail:
      "Les tranches sans exposition connue conservent leur valeur comptable entière plutôt que d’être réparties.",
    visualisation: "BREAKDOWN",
    pinnable: false,
    hideable: true,
  },
  {
    id: "attributable_net_worth",
    label: "Patrimoine attribuable",
    question: "Quelle part de ce patrimoine me revient vraiment ?",
    formula: "Patrimoine net pondéré par la quote-part détenue de chaque ligne",
    engine: "net-worth-attribution",
    conventions: [
      "Une quote-part détenue non déclarée ne vaut pas 100 % : la valeur attribuable devient non calculable.",
      "Une filiale détenue via une holding entre au patrimoine par la holding et par elle seule.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: ["Quote-part détenue déclarée"],
    requiredData: ["Quote-part détenue de chaque ligne partagée", "Patrimoine net"],
    optionalData: ["Démembrement déclaré", "Chaîne de détention par holding"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Votre part personnelle, quand un bien ou une société est détenu à plusieurs. Sans quote-part déclarée, elle n’est pas calculée : la supposer entière surévaluerait votre patrimoine.",
    technicalDetail: "Aucune quote-part n’est déduite d’un défaut : elle est déclarée ou absente.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "net_worth_change_since_close",
    label: "Évolution depuis la clôture",
    question: "Ma situation s’améliore-t-elle ou se dégrade-t-elle ?",
    formula: "Patrimoine net de la clôture courante − patrimoine net de la clôture comparable",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().history",
    conventions: [
      "N’afficher une variation QUE si deux clôtures comparables existent (section 9).",
      "Deux clôtures dont le périmètre ou la devise de reporting diffèrent ne sont pas comparables.",
    ],
    period: "USER_RANGE",
    currency: "REPORTING",
    minimalSources: ["Deux clôtures mensuelles persistées et comparables"],
    requiredData: ["Clôture courante", "Clôture de référence de même périmètre"],
    optionalData: ["Décomposition par domaine de la variation"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "NOT_COMPUTABLE",
    onPartialPeriod: "NOT_COMPUTABLE",
    provenance: "DERIVED",
    userExplanation:
      "L’écart avec votre dernière situation arrêtée. Il n’apparaît que si les deux arrêtés sont réellement comparables.",
    technicalDetail:
      "`history` porte mtd, m1, m3 et m12, chacun avec sa propre disponibilité de référence.",
    visualisation: "VALUE_WITH_DELTA",
    pinnable: true,
    hideable: false,
  },
  {
    id: "liquidity_coverage_months",
    label: "Mois de sécurité",
    question: "Combien de temps mes liquidités couvrent-elles mes charges ?",
    formula: "Liquidités disponibles ÷ sorties mensuelles incompressibles",
    engine:
      "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().liquidity.cashCoverageMonths",
    conventions: [
      "Le service de dette est incompressible et entre au dénominateur.",
      "Une catégorie essentielle sans montant déclaré rend la couverture surestimée : elle est signalée.",
    ],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: [OBSERVED_BALANCES, "Charges essentielles déclarées", CONTRACT],
    requiredData: ["Liquidité immédiate", "Sorties mensuelles incompressibles"],
    optionalData: ["Liquidités mobilisables sous préavis"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Le nombre de mois que vos liquidités couvrent, si vos revenus s’arrêtaient et que vos charges contraintes restaient.",
    technicalDetail:
      "Un dénominateur nul rend le ratio non calculable plutôt qu’infini : une absence de charge déclarée n’est pas une absence de charge.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: true,
  },

  // ─── Flux constatés ─────────────────────────────────────────────────────────────────
  {
    id: "observed_income",
    label: "Revenus encaissés",
    question: "Combien est réellement entré ce mois-ci ?",
    formula: "Somme des flux classés en revenu sur la période",
    engine: "cash-flow.computeObservedCashFlow().income",
    conventions: [
      "TRANSFERT ≠ DÉPENSE et un transfert interne n’est ni revenu ni dépense.",
      "Un remboursement d’achat corrige la dépense, il n’est pas un revenu.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [LEDGER],
    requiredData: ["Transactions classées de la période", "Profondeur d’historique déclarée"],
    optionalData: ["Rapprochement bulletin de paie"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation:
      "Ce qui est réellement entré sur vos comptes, hors virements que vous vous faites à vous-même.",
    technicalDetail:
      "Une transaction importée naît sans catégorie et est comptée comme non classée, jamais rangée d’office.",
    visualisation: "VALUE_WITH_DELTA",
    pinnable: true,
    hideable: true,
  },
  {
    id: "essential_expenses",
    label: "Dépenses incompressibles",
    question: "Quelle part de mes dépenses ne peut pas baisser ?",
    formula: "Somme des dépenses de catégories déclarées essentielles sur la période",
    engine: "cash-flow.computeObservedCashFlow().essentialExpenses",
    conventions: [
      "RÉCURRENT ≠ INCOMPRESSIBLE : la récurrence est une fréquence, l’essentialité un jugement déclaré.",
      "Une catégorie dont l’essentialité n’est pas déclarée reste inconnue, pas non essentielle.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [LEDGER, "Essentialité déclarée par catégorie"],
    requiredData: ["Transactions de dépense classées", "Essentialité de chaque catégorie"],
    optionalData: ["Comportement fixe ou variable de la catégorie"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation: "Ce que vous devez payer quoi qu’il arrive : logement, énergie, crédits.",
    technicalDetail: "L’essentialité vient de `expense_categories`, jamais du libellé.",
    visualisation: "VALUE_WITH_DELTA",
    pinnable: true,
    hideable: true,
  },
  {
    id: "free_cash_flow_after_debt",
    label: "Solde libre",
    question: "Quelle marge me reste-t-il après charges et crédits ?",
    formula: "Revenus − dépenses de consommation − impôts − service de dette",
    engine: "cash-flow.computeObservedCashFlow().cashFlowAfterDebt",
    conventions: [
      "PRINCIPAL ≠ CHARGE : le remboursement de capital sort de la trésorerie sans appauvrir.",
      "Le solde est calculé APRÈS service de dette, et le surplus avant dette est un agrégat distinct.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [LEDGER],
    requiredData: ["Revenus encaissés", "Dépenses classées", "Service de dette payé"],
    optionalData: ["Impôts payés sur la période"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation:
      "Ce qui reste après avoir tout payé, crédits compris. C’est la marge que vous pouvez affecter.",
    technicalDetail:
      "`cashFlowAfterDebt`, distinct de `operatingCashFlowBeforeDebt` et de `observedSavings`.",
    visualisation: "VALUE_WITH_DELTA",
    pinnable: true,
    hideable: true,
  },
  {
    id: "savings_rate",
    label: "Taux d’épargne",
    question: "Quelle part de mes revenus est-ce que j’épargne ?",
    formula: "Épargne constatée ÷ revenus encaissés de la période",
    engine: "cash-flow.computeObservedCashFlow().observedSavingsRate",
    conventions: [
      "Le dénominateur est le revenu ENCAISSÉ, pas le revenu brut.",
      "Sans revenu encaissé observé, le taux est non calculable : il n’est pas nul.",
    ],
    period: "MONTH",
    currency: null,
    minimalSources: [LEDGER],
    requiredData: ["Revenus encaissés", "Flux d’épargne classés"],
    optionalData: ["Flux d’investissement classés"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation: "La part de ce que vous encaissez qui finit en épargne plutôt qu’en dépense.",
    technicalDetail:
      "Un mois partiel est étiqueté comme tel : aucune annualisation implicite n’est faite.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "cash_runway",
    label: "Autonomie de trésorerie",
    question: "Jusqu’à quand ma trésorerie tient-elle au rythme actuel ?",
    formula: "Projection des soldes sous flux contractuels et récurrences confirmées",
    engine: "cash-flow.cashRunwayDays",
    conventions: [
      "Une récurrence DÉTECTÉE mais non confirmée n’entre pas dans la projection.",
      "Une fenêtre non intégralement couverte ne produit pas de moyenne mensuelle.",
    ],
    period: "USER_RANGE",
    currency: null,
    minimalSources: [OBSERVED_BALANCES, LEDGER, CONTRACT],
    requiredData: ["Liquidité immédiate", "Flux contractuels connus"],
    optionalData: ["Récurrences confirmées", "Échéances fiscales datées"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_COMPUTABLE",
    provenance: "CONTRACTUAL",
    userExplanation:
      "Le moment où votre trésorerie deviendrait tendue si rien ne changeait. Fondé sur vos engagements connus, pas sur une moyenne.",
    technicalDetail: "Aucune moyenne n’est calculée sur des mois dont la couverture est inconnue.",
    visualisation: "TIME_SERIES",
    pinnable: false,
    hideable: true,
  },
  {
    id: "unclassified_flows",
    label: "Flux non classés",
    question: "Que reste-t-il à ranger dans mes opérations ?",
    formula: "Somme des transactions sans catégorie économique sur la période",
    engine: "cash-flow.computeObservedCashFlow().unclassifiedFlows",
    conventions: ["Une transaction importée naît sans catégorie : c’est un état, pas une erreur."],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [LEDGER],
    requiredData: ["Transactions de la période"],
    optionalData: [],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation:
      "Le montant des opérations qui n’ont pas encore de catégorie. Elles ne sont comptées dans aucun agrégat tant qu’elles n’en ont pas.",
    technicalDetail: "Sert de mesure de complétude du ledger, pas de poste de dépense.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },

  // ─── Dette ──────────────────────────────────────────────────────────────────────────
  {
    id: "debt_outstanding",
    label: "Capital restant dû",
    question: "Combien me reste-t-il à rembourser ?",
    formula: "Encours observé le plus récent, ou encours contractuel à la date d’arrêté",
    engine: "debt.outstandingAt",
    conventions: [
      "CAPITAL EMPRUNTÉ ≠ ENCOURS ≠ COÛT FUTUR ≠ SORTIES DE TRÉSORERIE FUTURES : quatre grandeurs distinctes.",
      "Un encours observé prime sur un encours reconstruit, et la reconstruction est signalée.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: ["Encours observé et daté", CONTRACT],
    requiredData: ["Encours observé OU termes contractuels complets"],
    optionalData: ["Échéancier fourni par le prêteur", "Remboursements anticipés déclarés"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "OBSERVED",
    userExplanation:
      "Ce qu’il vous reste à rembourser en capital. Ce n’est ni le montant emprunté, ni le total que vous allez encore payer.",
    technicalDetail:
      "L’échéancier fourni domine la reconstruction ; une reconstruction est explicitement signalée.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: false,
  },
  {
    id: "next_cash_out",
    label: "Prochaine sortie de trésorerie",
    question: "Quand et combien sort-il de mon compte la prochaine fois ?",
    formula: "Montant total de la prochaine échéance débitée, assurance et frais compris",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().debt.nextCashOut",
    conventions: [
      "PREMIÈRE SORTIE DE TRÉSORERIE ≠ DÉBUT D’AMORTISSEMENT DU PRINCIPAL : un différé les sépare.",
      "Le montant est le DÉBIT total, pas la seule part de capital.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: [CONTRACT, "Échéancier fourni par le prêteur"],
    requiredData: ["Date de la prochaine échéance", "Montant total débité"],
    optionalData: ["Décomposition capital, intérêts, assurance, frais"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "CONTRACTUAL",
    userExplanation:
      "Le prochain prélèvement, tel qu’il apparaîtra sur votre relevé, assurance et frais inclus.",
    technicalDetail:
      "`debt.nextCashOut` et `debt.nextCashOutDate` viennent de l’échéancier contractuel ou fourni.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: false,
  },
  {
    id: "debt_service_30d",
    label: "Service de dette à 30 jours",
    question: "Combien mes crédits vont-ils me coûter en trésorerie ce mois-ci ?",
    formula: "Somme des débits contractuels des trente prochains jours",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().debt.service30d",
    conventions: ["CASH FLOW ≠ COÛT ÉCONOMIQUE : le service inclut le capital, le coût non."],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [CONTRACT],
    requiredData: ["Échéancier de chaque prêt sur la fenêtre"],
    optionalData: ["Assurance et frais récurrents déclarés"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "CONTRACTUAL",
    userExplanation:
      "Ce que vos crédits vont prélever dans les trente jours. C’est de la trésorerie, pas un coût.",
    technicalDetail: "Fenêtre glissante de 30 jours à partir de la date d’arrêté.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: true,
  },
  {
    id: "debt_future_cash_out",
    label: "Sorties futures totales",
    question: "Combien vais-je encore payer en tout ?",
    formula: "Somme de tous les débits restants : capital, intérêts, assurance et frais",
    engine: "debt.debtCashOut",
    conventions: [
      "Cette grandeur n’est PAS le capital restant dû, et la confondre avec lui gonfle la dette du montant des intérêts et de l’assurance.",
    ],
    period: "USER_RANGE",
    currency: "NATIVE",
    minimalSources: [CONTRACT, "Échéancier fourni par le prêteur"],
    requiredData: ["Échéancier complet jusqu’à la maturité"],
    optionalData: ["Indemnité de remboursement anticipé"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "CONTRACTUAL",
    userExplanation:
      "Le total de ce que vous allez encore débourser. Il est supérieur au capital restant dû, de tout ce qui n’est pas du capital.",
    technicalDetail:
      "Le cas CIC du plan de refonte est le golden case : 16 745 € de capital pour 17 116,45 € de sorties futures.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "debt_economic_cost_12m",
    label: "Coût économique sur 12 mois",
    question: "Que me coûtent réellement mes crédits, hors remboursement de capital ?",
    formula: "Intérêts + assurance + frais des douze prochains mois, capital exclu",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().debt.economicCost12m",
    conventions: [
      "Le remboursement de capital est neutre sur le patrimoine net : il n’est pas un coût.",
    ],
    period: "TRAILING_12M",
    currency: "REPORTING",
    minimalSources: [CONTRACT],
    requiredData: ["Décomposition de chaque échéance"],
    optionalData: ["Assurance emprunteur détaillée"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "CONTRACTUAL",
    userExplanation:
      "Le vrai coût de vos crédits : intérêts, assurance et frais. Le capital que vous remboursez n’est pas un coût, il éteint une dette.",
    technicalDetail: "Somme de `interest12m`, `insurance12m` et `fees12m`.",
    visualisation: "BREAKDOWN",
    pinnable: false,
    hideable: true,
  },
  {
    id: "debt_maturity",
    label: "Maturité",
    question: "Quand aurai-je fini de rembourser ?",
    formula: "Date de la dernière échéance de l’échéancier retenu",
    engine: "debt.buildContractualSchedule",
    conventions: [
      "Une maturité incohérente avec l’échéancier est signalée, jamais corrigée en silence.",
    ],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: [CONTRACT],
    requiredData: ["Échéancier ou nombre d’échéances et périodicité"],
    optionalData: ["Balloon déclaré"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "NOT_APPLICABLE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "CONTRACTUAL",
    userExplanation: "La date de votre dernière échéance.",
    technicalDetail: "Un balloon non renseigné rend la dernière échéance incomplète.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },

  // ─── Placements ─────────────────────────────────────────────────────────────────────
  {
    id: "portfolio_value",
    label: "Valeur du portefeuille",
    question: "Combien valent mes placements ?",
    formula: "Somme des valorisations observées des enveloppes d’investissement",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().structure.investedAssets",
    conventions: [
      "Un PEA observé à 20 000 € composé de 15 000 € d’ETF et 5 000 € de cash reste 20 000 €.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: [OBSERVED_BALANCES, OBSERVED_VALUATIONS],
    requiredData: ["Valorisation observée de chaque enveloppe"],
    optionalData: ["Positions détaillées", FX],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "OBSERVED",
    userExplanation:
      "La valeur de vos enveloppes. Les lignes qu’elles contiennent expliquent cette valeur, elles ne s’y ajoutent pas.",
    technicalDetail: "`structure.investedAssets`, distinct de `marketInvestedAssets`.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: false,
  },
  {
    id: "envelope_cash",
    label: "Cash d’enveloppe",
    question: "Combien de liquidités dorment dans mes enveloppes ?",
    formula: "Part non exposée au marché des enveloppes d’investissement",
    engine: "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().structure.investmentCash",
    conventions: [
      "Ce cash n’est PAS de la liquidité immédiate : il est dans une enveloppe, avec ses règles de retrait.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: [OBSERVED_BALANCES, "Positions de l’enveloppe"],
    requiredData: ["Valorisation de l’enveloppe", "Exposition de marché connue"],
    optionalData: [],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Les liquidités qui restent dans vos comptes-titres sans être investies. Elles ne comptent pas dans votre liquidité immédiate.",
    technicalDetail:
      "Une enveloppe dont l’exposition est inconnue ne produit pas de cash d’enveloppe déduit.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "portfolio_concentration",
    label: "Concentration",
    question: "Mon portefeuille est-il trop concentré sur une ligne ?",
    formula: "Poids de la plus grosse position de marché dans les actifs investis",
    engine:
      "balance-sheet-metrics.deriveCanonicalBalanceSheetMetrics().ratios.largestMarketPositionConcentration",
    conventions: ["La concentration exclut le cash d’enveloppe, et le signale."],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: ["Positions détaillées avec valorisation"],
    requiredData: ["Valorisation de chaque position", "Exposition de marché de l’enveloppe"],
    optionalData: ["Classe d’actifs et zone géographique"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation: "Le poids de votre plus grosse ligne. Un poids élevé est un risque de fond.",
    technicalDetail:
      "Une exposition d’enveloppe inconnue rend le ratio non calculable plutôt que sous-estimé.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "portfolio_twr",
    label: "Performance pondérée par le temps",
    question: "Quelle performance mes placements ont-ils réellement délivrée ?",
    formula: "TWR sur les sous-périodes délimitées par les flux externes datés",
    engine: "portfolio-analytics.buildPortfolioAnalytics",
    conventions: [
      "Exige une couverture temporelle DÉCLARÉE et des flux externes fiables (section 9).",
      "Un flux externe non rapproché invalide la sous-période qui le contient.",
    ],
    period: "USER_RANGE",
    currency: "REPORTING",
    minimalSources: [
      "Ledger portefeuille sur période déclarée couverte",
      "Valorisations d’ouverture et de clôture",
    ],
    requiredData: [
      "Couverture d’historique déclarée",
      "Flux externes datés et rapprochés",
      "Valorisations aux bornes de chaque sous-période",
    ],
    optionalData: ["Frais de transaction", "Retenues à la source"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_COMPUTABLE",
    provenance: "DERIVED",
    userExplanation:
      "La performance de vos placements indépendamment de vos versements. Elle n’apparaît que si l’historique nécessaire est complet : une performance calculée sur un historique troué serait fausse sans le dire.",
    technicalDetail:
      "Une métrique de performance sans ledger d’investissement ne produit que du non calculable.",
    visualisation: "TIME_SERIES",
    pinnable: false,
    hideable: true,
  },
  {
    id: "portfolio_xirr",
    label: "Taux de rendement de vos versements",
    question: "Qu’ont rapporté mes versements, compte tenu de leurs dates ?",
    formula: "XIRR sur les flux externes datés et la valeur finale",
    engine: "portfolio-analytics.buildPortfolioAnalytics",
    conventions: [
      "Des flux tous de même signe n’admettent pas de solution : le résultat est non calculable, pas nul.",
    ],
    period: "USER_RANGE",
    currency: null,
    minimalSources: ["Ledger portefeuille sur période déclarée couverte"],
    requiredData: ["Flux externes datés et signés", "Valeur finale observée"],
    optionalData: ["Frais et retenues"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_COMPUTABLE",
    provenance: "DERIVED",
    userExplanation:
      "Le rendement annualisé de votre argent, en tenant compte du moment où vous l’avez versé.",
    technicalDetail:
      "Plusieurs solutions ou aucune solution sont des états nommés, pas des valeurs approchées.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "unrealised_pnl",
    label: "Plus ou moins-value latente",
    question: "Combien mes lignes ont-elles gagné ou perdu, sans les vendre ?",
    formula: "Valorisation observée − coût de revient des lots ouverts",
    engine: "portfolio.buildPortfolioLedger",
    conventions: [
      "PnL RÉALISÉ ≠ PnL LATENT, et PnL MARCHÉ ≠ PnL DE CHANGE.",
      "Un coût de revient inconnu rend la latente non calculable : la supposer nulle inventerait une performance.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: ["Ledger portefeuille", OBSERVED_VALUATIONS],
    requiredData: ["Coût de revient des lots ouverts", "Valorisation observée"],
    optionalData: ["Méthode d’appariement des lots déclarée"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "L’écart entre ce que valent vos lignes et ce qu’elles vous ont coûté. Rien n’est encaissé tant que vous n’avez pas vendu.",
    technicalDetail:
      "Le ledger porte les faits ; les lots et le coût de revient en sont dérivés, jamais persistés.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },

  // ─── Immobilier ─────────────────────────────────────────────────────────────────────
  {
    id: "property_value",
    label: "Valeur du bien",
    question: "Que vaut ce bien aujourd’hui ?",
    formula: "Valorisation observée la plus récente, avec sa date et sa source",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: [
      "Une valorisation est une observation DATÉE : elle est signalée périmée, jamais indexée ni corrigée.",
      "Son absence est un montant inconnu, pas un bien sans valeur.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: ["Valorisation déclarée, expertise, notaire ou comparables acceptés"],
    requiredData: ["Valeur et date de valorisation"],
    optionalData: ["Fourchette", "Instantané de comparables"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "OBSERVED",
    userExplanation:
      "La dernière valeur estimée de votre bien, avec sa date. Une valeur ancienne reste affichée et signalée : elle n’est pas actualisée à votre place.",
    technicalDetail: "La péremption est DÉRIVÉE à la lecture et n’est jamais persistée.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: false,
  },
  {
    id: "property_total_cost",
    label: "Coût de revient",
    question: "Combien ce bien m’a-t-il coûté en tout ?",
    formula: "prix + frais d’acquisition + travaux capitalisés + coûts directs",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: [
      "COÛT DE REVIENT ≠ VALEUR DE MARCHÉ.",
      "Un dépôt d’acquisition imputé au prix n’est pas un coût doublé.",
      "L’absence d’événement de frais ou de capex ne vaut pas zéro : une déclaration explicite, y compris à 0, est requise.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: ["Acte d’acquisition", "Factures de travaux"],
    requiredData: [
      "Prix d’acquisition",
      "Frais d’acquisition déclarés, même à zéro",
      "Capex déclaré, même à zéro",
    ],
    optionalData: ["Coûts directs de portage"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "OBSERVED",
    userExplanation:
      "Tout ce que ce bien vous a coûté : prix, frais de notaire, travaux. Sans déclaration de frais, même à zéro, le coût n’est pas calculé.",
    technicalDetail: "Un événement futur ne modifie jamais une lecture présente.",
    visualisation: "BREAKDOWN",
    pinnable: false,
    hideable: true,
  },
  {
    id: "property_equity",
    label: "Valeur nette du bien",
    question: "Quelle part du bien m’appartient réellement, crédit déduit ?",
    formula: "Valeur du bien − dette attribuée par quote-part de financement",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: [
      "L’absence de dette rattachée n’est pas une absence de dette : seul un zéro DÉCLARÉ autorise à calculer une equity.",
      "La quote-part d’un concours affectée à des biens ne dépasse jamais 1.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: ["Valorisation du bien", "Rattachement de dette ou absence déclarée"],
    requiredData: ["Valeur du bien", "Dette attribuée OU absence de dette déclarée"],
    optionalData: ["Quote-part détenue"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Ce que le bien vous rapporterait après remboursement du crédit. Tant que vous n’avez pas déclaré l’absence de dette, le calcul reste ouvert : le supposer sans dette surévaluerait votre patrimoine.",
    technicalDetail:
      "La quote-part de financement est un invariant de base, pas un contrôle applicatif.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "property_gross_yield",
    label: "Rendement brut",
    question: "Que rapporte ce bien par rapport à son prix ?",
    formula: "Loyer annuel ÷ dénominateur NOMMÉ (prix d’acquisition ou valeur actuelle)",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: [
      "Le rendement brut indique TOUJOURS son dénominateur : prix d’acquisition et valeur actuelle donnent deux chiffres différents.",
    ],
    period: "YEAR",
    currency: null,
    minimalSources: ["Bail ou loyers observés", "Prix d’acquisition ou valorisation"],
    requiredData: ["Loyer annuel", "Dénominateur choisi et déclaré"],
    optionalData: ["Vacance déclarée"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "DERIVED",
    userExplanation:
      "Le loyer annuel rapporté au prix. Le dénominateur est indiqué, parce que rapporter au prix payé ou à la valeur du jour ne donne pas le même chiffre.",
    technicalDetail: "Aucun dénominateur par défaut n’est appliqué.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "property_noi",
    label: "Résultat d’exploitation net",
    question: "Que reste-t-il du loyer après charges ?",
    formula:
      "EGI − charges d’exploitation, où EGI = loyer contractuel − vacance/pertes + autres revenus",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: [
      "Le NOI exclut le principal, les intérêts, l’impôt sur le revenu et le capex.",
      "Une charge d’exploitation déclarée à zéro est une information ; une charge non déclarée n’en est pas une.",
    ],
    period: "YEAR",
    currency: "NATIVE",
    minimalSources: ["Bail", "Charges d’exploitation déclarées"],
    requiredData: [
      "Loyer contractuel",
      "Vacance déclarée",
      "Chaque charge d’exploitation déclarée",
    ],
    optionalData: ["Autres revenus du bien"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "DERIVED",
    userExplanation:
      "Ce que le bien rapporte après ses charges, avant crédit et impôt. Une charge non déclarée rend le calcul impossible : la compter nulle gonflerait le rendement.",
    technicalDetail: "Les provisions de charges locatives ne sont pas automatiquement un revenu.",
    visualisation: "BREAKDOWN",
    pinnable: false,
    hideable: true,
  },
  {
    id: "property_ltv",
    label: "Quotité de financement",
    question: "Quelle part du bien est financée à crédit ?",
    formula: "Dette attribuée ÷ valeur du bien",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: ["Le dénominateur est la valeur du bien, pas son coût de revient."],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: ["Valorisation du bien", "Rattachement de dette"],
    requiredData: ["Dette attribuée", "Valeur du bien"],
    optionalData: [],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation: "La part du bien encore financée par votre crédit.",
    technicalDetail: "Une dette non rattachée n’est pas attribuée : le ratio reste ouvert.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "property_dscr",
    label: "Couverture du service de dette",
    question: "Le bien couvre-t-il ses propres échéances ?",
    formula: "NOI ÷ service de dette annuel attribué",
    engine: "real-estate.buildRealEstatePortfolio",
    conventions: [
      "N’apparaît qu’avec des flux ET une dette réellement rattachés (section 9).",
      "Un dénominateur nul rend le ratio non calculable, jamais infini.",
    ],
    period: "YEAR",
    currency: null,
    minimalSources: ["Charges et loyers déclarés", "Rattachement de dette", CONTRACT],
    requiredData: ["Résultat d’exploitation net", "Service de dette attribué"],
    optionalData: [],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "NOT_COMPUTABLE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_COMPUTABLE",
    provenance: "DERIVED",
    userExplanation:
      "Si le résultat du bien suffit à payer ses échéances. En dessous de 1, vous complétez de votre poche.",
    technicalDetail: "Exige que la dette soit rattachée par quote-part au bien.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },

  // ─── Carrière ───────────────────────────────────────────────────────────────────────
  {
    id: "gross_compensation",
    label: "Rémunération brute",
    question: "Combien mon activité me rapporte-t-elle en brut ?",
    formula: "Somme des termes de rémunération en vigueur, annualisés sur les faits datés",
    engine: "career.buildCareerAnalytics",
    conventions: ["Un mois dont un terme est inconnu ne produit pas d’annualisation."],
    period: "YEAR",
    currency: "NATIVE",
    minimalSources: ["Contrat, avenant ou bulletin de paie"],
    requiredData: ["Rémunération de base datée"],
    optionalData: ["Variable cible", "Avantages en nature"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "CONTRACTUAL",
    userExplanation: "Votre rémunération brute annuelle, telle que vos contrats la définissent.",
    technicalDetail: "`annualisedFixedCompensation`, calculé sur le mois de la date d’arrêté.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "net_cash_received",
    label: "Net réellement encaissé",
    question: "Combien arrive vraiment sur mon compte ?",
    formula: "Somme des virements de salaire observés au ledger sur la période",
    engine: "career-tax-cash-flow.toCareerTaxCashFlow",
    conventions: [
      "Ne pas fabriquer un net à partir d’un brut sans règle ou preuve (section 9).",
      "Le rapprochement bulletin/banque ne force jamais un bulletin = un virement.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [LEDGER, "Bulletin de paie"],
    requiredData: ["Virements de salaire observés"],
    optionalData: ["Bulletin rapproché", "Acomptes et remboursements de frais"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation:
      "Ce qui a réellement été viré sur votre compte. Sans règle fiscale ou bulletin, ce montant n’est pas déduit de votre brut.",
    technicalDetail:
      "Un encaissement déjà compté au mois de paie est signalé, pas compté deux fois.",
    visualisation: "VALUE_WITH_DELTA",
    pinnable: false,
    hideable: true,
  },

  // ─── Entreprises ────────────────────────────────────────────────────────────────────
  {
    id: "business_equity_value",
    label: "Valeur des titres",
    question: "Que valent mes parts dans cette société ?",
    formula: "Enterprise Value − dette brute + trésorerie ± autres éléments du pont, datés",
    engine: "business-valuation.valueBusiness",
    conventions: [
      "EV ≠ EQUITY VALUE : une Enterprise Value connue sans dette brute ni trésorerie datées ne produit aucune Equity Value.",
      "Les autres éléments du pont ne valent zéro que si leur complétude est explicitement déclarée.",
    ],
    period: "POINT_IN_TIME",
    currency: "NATIVE",
    minimalSources: ["Liasse fiscale, comptes annuels, FEC ou transaction observée"],
    requiredData: [
      "Base de valorisation déclarée",
      "Dette brute datée",
      "Trésorerie datée",
      "Complétude du pont déclarée",
    ],
    optionalData: ["Retraitements d’EBITDA", "Éléments de pont détaillés"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "La valeur de vos titres, une fois la dette de la société déduite et sa trésorerie ajoutée. Sans ces deux montants datés, la valeur des titres n’est pas calculée.",
    technicalDetail:
      "Aucune valorisation dérivée n’est persistée : une contrainte de base l’interdit. Le résultat est produit à la lecture.",
    visualisation: "WATERFALL",
    pinnable: false,
    hideable: false,
  },
  {
    id: "business_attributable_value",
    label: "Valeur qui me revient",
    question: "Quelle part de cette valeur m’appartient ?",
    formula: "Valeur des titres × quote-part économique détenue, en transparence des holdings",
    engine: "business-equity.buildBusinessEquityPortfolio",
    conventions: [
      "DETTE CORPORATE ≠ DETTE PERSONNELLE.",
      "Une filiale détenue via une holding entre au patrimoine par la holding et par elle seule.",
    ],
    period: "POINT_IN_TIME",
    currency: "REPORTING",
    minimalSources: ["Cap table, acte ou registre"],
    requiredData: ["Valeur des titres", "Quote-part économique déclarée"],
    optionalData: ["Chaîne de détention indirecte", "Droits préférentiels"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation: "Ce que votre participation représente dans votre patrimoine personnel.",
    technicalDetail:
      "Une détention en transparence supérieure à 100 % est signalée, pas plafonnée.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: false,
  },
  {
    id: "business_distributions",
    label: "Flux reçus de la société",
    question: "Combien cette société m’a-t-elle versé ?",
    formula: "Somme des dividendes, remboursements de compte courant et cessions encaissés",
    engine: "business-capital",
    conventions: [
      "DIVIDENDE ≠ CONTRIBUTION : un versement reçu n’est pas un apport.",
      "Un flux de société non rapproché du ledger reste signalé.",
    ],
    period: "USER_RANGE",
    currency: "NATIVE",
    minimalSources: ["Décisions de distribution", LEDGER],
    requiredData: ["Flux de capital datés"],
    optionalData: ["Retenues et fiscalité applicables"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation: "Ce que la société vous a effectivement versé, à ce jour.",
    technicalDetail:
      "Une distribution répartie au prorata faute de décision nominative est signalée comme telle.",
    visualisation: "TABLE",
    pinnable: false,
    hideable: true,
  },

  // ─── Fiscalité ──────────────────────────────────────────────────────────────────────
  {
    id: "tax_paid",
    label: "Impôt payé",
    question: "Qu’ai-je réellement payé ?",
    formula: "Somme des retenues et paiements d’impôt observés sur l’année",
    engine: "tax.calculateEmploymentTax",
    conventions: ["PRE_TAX ≠ AFTER_TAX_ESTIMATED ≠ AFTER_TAX_VERIFIED : trois natures distinctes."],
    period: "YEAR",
    currency: "REPORTING",
    minimalSources: ["Avis d’imposition, bulletin de paie ou relevé bancaire"],
    requiredData: ["Observations fiscales datées"],
    optionalData: ["Crédits et remboursements"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "OBSERVED",
    userExplanation: "L’impôt réellement prélevé ou payé, tel que vos documents l’attestent.",
    technicalDetail: "Une observation fiscale est un fait daté, distincte de toute estimation.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },
  {
    id: "tax_estimate",
    label: "Impôt estimé",
    question: "Que me reste-t-il potentiellement dû ?",
    formula: "Application des règles fiscales DÉCLARÉES et versionnées aux revenus constatés",
    engine: "tax.calculateEmploymentTax",
    conventions: [
      "Une absence de règle n’est JAMAIS présentée comme 0 € (section 9).",
      "Les règles portent effectiveFrom, effectiveTo, source, vérification et version.",
    ],
    period: "YEAR",
    currency: "REPORTING",
    minimalSources: ["Jeu de règles fiscales déclaré pour l’année", "Revenus constatés"],
    requiredData: ["Foyer fiscal déclaré", "Jeu de règles de l’année en vigueur", "Revenus datés"],
    optionalData: ["Déductions et crédits déclarés"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "DERIVED",
    userExplanation:
      "Une estimation, calculée avec les règles que vous avez renseignées. Sans règle, aucun montant n’est affiché : un zéro laisserait croire que vous ne devez rien.",
    technicalDetail:
      "Les règles ne sont pas des constantes éternelles : elles sont datées et versionnées.",
    visualisation: "RANGE",
    pinnable: false,
    hideable: false,
  },

  // ─── Objectifs ──────────────────────────────────────────────────────────────────────
  {
    id: "goal_progress",
    label: "Progression",
    question: "Où en suis-je sur cet objectif ?",
    formula: "Valeur courante de l’indicateur de l’objectif, rapportée à sa cible",
    engine: "goal-metrics.resolveCurrentGoalMetric",
    conventions: [
      "Un objectif atteint aujourd’hui peut rester non projetable : les deux états ne sont pas confondus.",
      "Une progression réellement égale à zéro reste zéro ; une progression inconnue reste non calculable.",
    ],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: ["Bilan canonique", "Définition d’objectif versionnée"],
    requiredData: ["Indicateur cible", "Valeur courante de l’indicateur"],
    optionalData: ["Montant déjà constitué déclaré"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "NOT_COMPUTABLE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Où vous en êtes, mesuré sur votre situation réelle et non sur une projection.",
    technicalDetail:
      "Une devise d’objectif différente de celle de sa mesure rend le calcul ouvert.",
    visualisation: "SINGLE_VALUE",
    pinnable: true,
    hideable: false,
  },
  {
    id: "goal_monthly_effort",
    label: "Effort mensuel nécessaire",
    question: "Combien dois-je mettre de côté chaque mois pour y arriver ?",
    formula: "Écart à la cible réparti sur les mois restants jusqu’à l’échéance",
    engine: "goal-engine",
    conventions: [
      "La projection dépend d’un scénario EXPLICITEMENT choisi (section 9).",
      "Une échéance postérieure à l’horizon du scénario est signalée, pas tronquée.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: ["Définition d’objectif versionnée", "Scénario sélectionné"],
    requiredData: ["Écart à la cible", "Échéance", "Scénario de projection choisi"],
    optionalData: ["Contribution prévue déclarée"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "NOT_COMPUTABLE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "SIMULATED",
    userExplanation:
      "Le versement mensuel qui vous amènerait à votre cible à la date voulue, dans le scénario que vous avez choisi.",
    technicalDetail: "Aucun scénario par défaut n’est appliqué : il est sélectionné.",
    visualisation: "SINGLE_VALUE",
    pinnable: false,
    hideable: true,
  },

  // ─── Scénarios et décisions ─────────────────────────────────────────────────────────
  {
    id: "scenario_trajectory",
    label: "Trajectoire simulée",
    question: "Où vais-je si je ne change rien ?",
    formula: "Projection mensuelle du modèle financier sous les hypothèses du scénario",
    engine: "monthly-financial-model",
    conventions: [
      "Une hypothèse ne devient jamais un fait : la trajectoire est marquée SIMULÉE.",
      "L’immobilier et Business Equity y entrent à valeur CONSTANTE et signalée, faute de termes projetables.",
      "L’inflation est versionnée et appliquée selon des horizons explicites, jamais uniformément.",
    ],
    period: "USER_RANGE",
    currency: "REPORTING",
    minimalSources: ["Bilan canonique", "Version de scénario"],
    requiredData: ["Hypothèses de marché déclarées", "Horizon", "Bilan de départ"],
    optionalData: ["Événements ponctuels", "Chocs déclarés"],
    onNull: "NOT_COMPUTABLE",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "SIMULATED",
    userExplanation:
      "Où votre situation irait sous les hypothèses affichées. Ce n’est pas une prévision : changez une hypothèse, la trajectoire change.",
    technicalDetail:
      "Le nombre de simulations n’est pas un indicateur de qualité si le modèle est simplifié.",
    visualisation: "TIME_SERIES",
    pinnable: false,
    hideable: false,
  },
  {
    id: "decision_option_comparison",
    label: "Comparaison des options",
    question: "Quel arbitrage répond le mieux à mon objectif ?",
    formula: "Conséquences de chaque option sur les critères DÉCLARÉS par l’utilisateur",
    engine: "decision-lab",
    conventions: [
      "Aucun score opaque et aucune recommandation automatique sans politique déclarée.",
      "Les points non comparables sont montrés comme non comparables, pas arbitrés.",
    ],
    period: "USER_RANGE",
    currency: "REPORTING",
    minimalSources: ["Cas de décision versionné", "Scénario associé à chaque option"],
    requiredData: ["Deux ou trois options", "Objectif principal", "Critères et leur ordre"],
    optionalData: ["Contraintes non négociables", "Données restant incertaines"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "SIMULATED",
    userExplanation:
      "Les conséquences de chaque option, sur les critères que vous avez choisis. Aucun vainqueur n’est désigné à votre place.",
    technicalDetail:
      "L’explicabilité peut reformuler les compromis, à partir des preuves citées uniquement.",
    visualisation: "TABLE",
    pinnable: false,
    hideable: false,
  },

  // ─── Sources et rapports ────────────────────────────────────────────────────────────
  {
    id: "source_freshness",
    label: "Fraîcheur des sources",
    question: "Mes données sont-elles à jour ?",
    formula: "Date de dernière mise à jour de chaque source, rapportée à la date opérationnelle",
    engine: null,
    conventions: [
      "Une donnée ancienne n’est pas supprimée : elle est datée, signalée si matérielle, et remplacée seulement par une nouvelle observation.",
    ],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: ["Sessions d’import", "Connexions déclarées", "Documents datés"],
    requiredData: ["Date de dernière mise à jour de chaque source"],
    optionalData: ["Période couverte déclarée"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "NOT_APPLICABLE",
    onForeignCurrency: "NOT_APPLICABLE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "OBSERVED",
    userExplanation: "Quand chacune de vos sources a été mise à jour pour la dernière fois.",
    technicalDetail: "La péremption est dérivée à la lecture, jamais persistée.",
    visualisation: "TABLE",
    pinnable: false,
    hideable: false,
  },
  {
    id: "pending_review_count",
    label: "Éléments à vérifier",
    question: "Que dois-je clarifier ?",
    formula: "Nombre de réserves dont l’état demande une intervention, par famille d’inbox",
    engine: null,
    conventions: [
      "Un domaine déclaré non concerné n’est pas une tâche : c’est une réponse.",
      "La matérialité combine montant absolu, relatif, importance du domaine et impact ; pas de seuil universel caché.",
    ],
    period: "POINT_IN_TIME",
    currency: null,
    minimalSources: ["Réserves des moteurs de domaine"],
    requiredData: ["Réserves traduites et classées par famille"],
    optionalData: ["Seuils de matérialité déclarés par l’utilisateur"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "NOT_APPLICABLE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "DERIVED",
    userExplanation:
      "Ce qui attend une décision de votre part, regroupé par nature : données manquantes, à confirmer, conflits, incidents.",
    technicalDetail:
      "Aucun code n’est promu en tâche priorisée par un agent : c’est une décision humaine par domaine.",
    visualisation: "BREAKDOWN",
    pinnable: true,
    hideable: false,
  },
  {
    id: "upcoming_obligations_30d",
    label: "Échéances à 30 jours",
    question: "Qu’est-ce qui tombe dans le mois ?",
    formula: "Événements contractuels et obligations datées des trente prochains jours",
    engine: "event-engine",
    conventions: [
      "Une échéance est CONTRACTUELLE ou déclarée : elle n’est jamais déduite d’une récurrence non confirmée.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: [CONTRACT, "Cycle de vie documentaire", "Échéances fiscales déclarées"],
    requiredData: ["Événements datés sur la fenêtre"],
    optionalData: ["Montant attendu de chaque échéance"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "NOT_APPLICABLE",
    provenance: "CONTRACTUAL",
    userExplanation:
      "Ce qui arrive dans les trente jours : échéances de crédit, impôts, fins de bail, expirations.",
    technicalDetail: "Les obligations documentaires alimentent cette fenêtre au même titre.",
    visualisation: "TABLE",
    pinnable: true,
    hideable: false,
  },
  {
    id: "close_summary",
    label: "Situation à la clôture",
    question: "Que s’est-il passé depuis la dernière revue ?",
    formula: "Agrégats du bilan canonique et des flux à la date de clôture retenue",
    engine: "presentation/historical-closes",
    conventions: [
      "La date de clôture est IMMUABLE dans un rapport, contrairement à la date opérationnelle.",
      "Aucune variation n’est affichée si les deux clôtures ne sont pas comparables.",
    ],
    period: "MONTH",
    currency: "REPORTING",
    minimalSources: ["Clôture mensuelle persistée"],
    requiredData: ["Clôture de la période", "Agrégats du bilan à cette date"],
    optionalData: ["Clôture de référence", "Décisions enregistrées sur la période"],
    onNull: "EXCLUDE_AND_FLAG",
    onDeclaredZero: "COMPUTE",
    onForeignCurrency: "CONVERT_AT_ECONOMIC_DATE",
    onPartialPeriod: "LABEL_AS_PARTIAL",
    provenance: "DERIVED",
    userExplanation: "Votre situation telle qu’elle a été arrêtée, et ce qui a changé depuis.",
    technicalDetail: "Un rapport consomme les mêmes moteurs que l’écran, jamais un second calcul.",
    visualisation: "TABLE",
    pinnable: false,
    hideable: false,
  },
]);
