import type { ObjectiveManifest } from "./contracts";

/**
 * Registre des objectifs (section 16.2 du plan de refonte).
 *
 * Un objectif est ce que l'utilisateur veut OBTENIR, pas une case de configuration. La
 * section 18.1 en fait la première question de tout formulaire long : « que souhaitez-vous
 * obtenir ? ». C'est ce qui renverse la charge : le produit ne demande plus de remplir un
 * modèle de données, il demande ce qu'on cherche puis ne révèle que les champs qui y mènent.
 *
 * Les entrées sont TRANSCRITES des tables « Options à cocher » et « Objectifs à cocher » des
 * sections 21 à 30. Aucun objectif n'est inventé : la section 16 interdit à une IA de décider
 * quels champs sont obligatoires ou quels KPI sont prioritaires.
 *
 * `humanJudgementRemains` n'est pas une précaution rédactionnelle. La section 38-9 liste les
 * sujets qui ne sont JAMAIS auto-validés : Quality of Earnings, synergies, multiples privés,
 * croissance salariale, valeur future, position fiscale ambiguë, propriété, debt-like,
 * récurrence, capex contre réparation, comparables faibles, préférences de liquidation.
 * Cocher un objectif ne délègue jamais ces jugements au produit.
 */

function manifests(
  entries: readonly ObjectiveManifest[],
): Readonly<Record<string, ObjectiveManifest>> {
  const map: Record<string, ObjectiveManifest> = {};
  for (const entry of entries) map[entry.id] = entry;
  return map;
}

export const OBJECTIVE_REGISTRY = manifests([
  // ─── Patrimoine (section 21) ────────────────────────────────────────────────────────
  {
    id: "manage_shared_ownership",
    label: "Gérer une détention partagée",
    reason:
      "Un bien ou un compte détenu à plusieurs ne vous appartient pas en entier : sans quote-part, votre patrimoine est surévalué.",
    revealsFieldGroups: ["co_titulaires", "quotes_parts", "indivision"],
    unlocksKpis: ["attributable_net_worth"],
    recommendedSources: ["Acte notarié", "Convention d’indivision", "Relevé de compte joint"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Qualification de la propriété entre indivisaires"],
  },
  {
    id: "represent_dismemberment",
    label: "Représenter un usufruit ou une nue-propriété",
    reason:
      "La propriété juridique, économique et le bénéfice ne coïncident pas dans un démembrement.",
    revealsFieldGroups: ["droits_juridiques", "droits_economiques", "dates_de_demembrement"],
    unlocksKpis: ["attributable_net_worth"],
    recommendedSources: ["Acte de donation", "Acte notarié"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: ["Valorisation respective de l’usufruit et de la nue-propriété"],
  },
  {
    id: "represent_holding",
    label: "Représenter une holding",
    reason:
      "Une filiale détenue via une holding entre au patrimoine par la holding, et par elle seule : sans cette chaîne, elle est comptée deux fois.",
    revealsFieldGroups: ["societe_interposee", "detention_indirecte"],
    unlocksKpis: ["business_attributable_value"],
    recommendedSources: ["Cap table", "Registre d’entreprises", "Statuts"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Qualification du contrôle effectif"],
  },
  {
    id: "track_liquidity",
    label: "Suivre ma liquidité",
    reason: "Savoir ce qui est mobilisable, et en combien de temps, avant d’en avoir besoin.",
    revealsFieldGroups: ["delai_de_mobilisation", "penalites_de_sortie", "profondeur_de_marche"],
    unlocksKpis: ["immediate_cash", "liquidity_coverage_months"],
    recommendedSources: ["Conditions du contrat", "Relevé de compte"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Profondeur réelle du marché d’un actif peu liquide"],
  },
  {
    id: "track_net_worth_change",
    label: "Suivre mon évolution",
    reason: "Comparer deux situations arrêtées, plutôt que deux instantanés non comparables.",
    revealsFieldGroups: ["clotures", "valeurs_comparables"],
    unlocksKpis: ["net_worth_change_since_close", "close_summary"],
    recommendedSources: ["Clôture mensuelle"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Comparabilité de deux périmètres qui ont changé"],
  },

  // ─── Flux (section 22) ──────────────────────────────────────────────────────────────
  {
    id: "understand_budget",
    label: "Comprendre mon budget",
    reason: "Distinguer ce que vous devez payer de ce que vous choisissez de dépenser.",
    revealsFieldGroups: ["revenu_disponible", "categories_economiques", "essentialite"],
    unlocksKpis: ["observed_income", "essential_expenses", "free_cash_flow_after_debt"],
    recommendedSources: ["Relevé bancaire CSV", "Connexion bancaire"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Caractère essentiel d’une dépense, qui vous appartient"],
  },
  {
    id: "measure_savings",
    label: "Mesurer mon épargne",
    reason: "Savoir ce qui reste vraiment, et où il va.",
    revealsFieldGroups: ["affectation_du_solde", "objectif_et_horizon"],
    unlocksKpis: ["savings_rate", "free_cash_flow_after_debt"],
    recommendedSources: ["Relevé bancaire CSV", "Connexion bancaire"],
    dependsOn: ["understand_budget"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "build_safety_fund",
    label: "Constituer un fonds de sécurité",
    reason: "Chiffrer combien de mois vous tiendriez, plutôt que de l’estimer au ressenti.",
    revealsFieldGroups: ["depenses_essentielles", "revenus_stables", "liquidites_disponibles"],
    unlocksKpis: ["liquidity_coverage_months", "immediate_cash"],
    recommendedSources: ["Relevé bancaire CSV"],
    dependsOn: ["understand_budget"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Niveau de sécurité souhaité, qui n’est pas une norme"],
  },
  {
    id: "detect_recurrences",
    label: "Détecter mes récurrences",
    reason:
      "Retrouver les prélèvements réguliers, sans les confondre avec des dépenses ponctuelles.",
    revealsFieldGroups: ["frequence", "date_attendue", "tolerance_de_montant"],
    unlocksKpis: ["cash_runway", "upcoming_obligations_30d"],
    recommendedSources: ["Relevé bancaire CSV", "Connexion bancaire"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: [
      "Confirmation d’une récurrence détectée : une ressemblance n’est pas une preuve",
    ],
  },
  {
    id: "forecast_treasury",
    label: "Prévoir ma trésorerie",
    reason: "Voir venir une tension de trésorerie avant qu’elle n’arrive.",
    revealsFieldGroups: ["flux_contractuels", "echeances", "soldes"],
    unlocksKpis: ["cash_runway", "upcoming_obligations_30d", "debt_service_30d"],
    recommendedSources: ["Échéancier de prêt", "Échéances fiscales", "Relevé bancaire"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "stress_income_drop",
    label: "Tester une baisse de revenu",
    reason: "Mesurer la marge qui resterait, et à quelle date la tension apparaîtrait.",
    revealsFieldGroups: ["ampleur_du_choc", "duree_du_choc", "depenses_reductibles"],
    unlocksKpis: ["scenario_trajectory", "cash_runway"],
    recommendedSources: [],
    dependsOn: ["understand_budget"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Réductibilité réelle d’une dépense sous contrainte"],
  },

  // ─── Placements (section 23) ────────────────────────────────────────────────────────
  {
    id: "see_allocation",
    label: "Voir ma répartition",
    reason: "Savoir sur quoi vous êtes réellement exposé, plutôt que par enveloppe.",
    revealsFieldGroups: ["positions", "quantites", "prix", "classes_dactifs", "devises"],
    unlocksKpis: ["asset_allocation", "portfolio_concentration", "envelope_cash"],
    recommendedSources: ["Import de portefeuille CSV ou XLSX", "Relevé de compte-titres"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Classement d’un instrument composite en classe d’actifs"],
  },
  {
    id: "measure_performance",
    label: "Mesurer ma performance",
    reason:
      "Séparer ce que vos placements ont produit de ce que vos versements ont apporté. Sans historique complet, aucune des deux mesures n’est fiable.",
    revealsFieldGroups: [
      "flux_externes_dates",
      "valeurs_douverture_et_de_cloture",
      "couts_de_transaction",
    ],
    unlocksKpis: ["portfolio_twr", "portfolio_xirr", "unrealised_pnl"],
    recommendedSources: ["Ledger de portefeuille", "Avis d’opéré", "Relevé annuel"],
    dependsOn: ["see_allocation"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: ["Déclaration de la profondeur d’historique réellement couverte"],
  },
  {
    id: "understand_investment_risk",
    label: "Comprendre mon risque",
    reason: "Voir la concentration et la liquidité de ce que vous détenez.",
    revealsFieldGroups: ["historique_de_prix", "exposition", "liquidite_des_lignes"],
    unlocksKpis: ["portfolio_concentration"],
    recommendedSources: ["Import de portefeuille", "Données de marché"],
    dependsOn: ["see_allocation"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Tolérance au risque, qui n’est pas déductible du portefeuille"],
  },
  {
    id: "project_portfolio",
    label: "Projeter mes placements",
    reason: "Voir une trajectoire possible, en gardant les hypothèses visibles et modifiables.",
    revealsFieldGroups: ["rendement_attendu", "volatilite", "contributions", "horizon"],
    unlocksKpis: ["scenario_trajectory"],
    recommendedSources: [],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Rendement et volatilité attendus, qui restent vos hypothèses"],
  },

  // ─── Dette (section 24) ─────────────────────────────────────────────────────────────
  {
    id: "loan_has_deferral",
    label: "Mon prêt comporte un différé",
    reason:
      "Un différé sépare la première sortie de trésorerie du début d’amortissement du capital : sans lui, l’échéancier est faux.",
    revealsFieldGroups: [
      "type_de_differe",
      "dates_de_differe",
      "interets_intercalaires",
      "assurance_pendant_differe",
    ],
    unlocksKpis: ["next_cash_out", "debt_future_cash_out", "debt_maturity"],
    recommendedSources: ["Offre de prêt", "Échéancier bancaire", "Contrat"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Traitement des intérêts intercalaires : payés ou capitalisés"],
  },
  {
    id: "loan_variable_rate",
    label: "Mon taux est variable",
    reason: "Un taux variable ne se projette pas sans son indice, sa marge et ses bornes.",
    revealsFieldGroups: ["benchmark", "marge", "date_de_reset", "floor_et_cap"],
    unlocksKpis: ["debt_service_30d", "debt_economic_cost_12m"],
    recommendedSources: ["Contrat", "Avenant"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Trajectoire future de l’indice, qui reste une hypothèse"],
  },
  {
    id: "loan_insurance_varies",
    label: "Mon assurance emprunteur varie",
    reason: "Une assurance dégressive change le coût futur sans changer le capital.",
    revealsFieldGroups: ["lignes_dassurance", "quotite", "beneficiaires"],
    unlocksKpis: ["debt_economic_cost_12m", "debt_future_cash_out"],
    recommendedSources: ["Contrat d’assurance emprunteur", "Échéancier bancaire"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "loan_has_fees",
    label: "J’ai plusieurs frais sur ce prêt",
    reason: "Les frais changent le coût total et, s’ils sont financés, le capital emprunté.",
    revealsFieldGroups: ["frais_de_dossier", "garantie", "courtage", "autres_frais"],
    unlocksKpis: ["debt_economic_cost_12m", "debt_future_cash_out"],
    recommendedSources: ["Offre de prêt", "FISE"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Frais financés ou payés comptant"],
  },
  {
    id: "loan_link_to_asset",
    label: "Rattacher ce prêt à un bien ou une société",
    reason:
      "Sans rattachement, la dette existe au passif mais aucune valeur nette de bien n’est calculable.",
    revealsFieldGroups: ["objet_finance", "quote_part_affectee"],
    unlocksKpis: ["property_equity", "property_ltv", "property_dscr"],
    recommendedSources: ["Acte d’acquisition", "Contrat de prêt"],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Répartition d’un concours entre plusieurs biens"],
  },
  {
    id: "loan_simulate_early_repayment",
    label: "Simuler un remboursement anticipé",
    reason: "Comparer l’économie complète à la liquidité qu’il consomme.",
    revealsFieldGroups: [
      "date_de_remboursement",
      "montant",
      "indemnite",
      "assurance_et_frais_evites",
    ],
    unlocksKpis: ["debt_future_cash_out", "decision_option_comparison"],
    recommendedSources: ["Décompte anticipé de la banque"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Arbitrage entre désendettement et liquidité conservée"],
  },

  // ─── Immobilier (section 25) ────────────────────────────────────────────────────────
  {
    id: "property_track_value",
    label: "Suivre la valeur du bien",
    reason: "Garder une valeur datée et sourcée, plutôt qu’une estimation de mémoire.",
    revealsFieldGroups: ["comparables", "expertise", "etat_du_bien", "travaux_realises"],
    unlocksKpis: ["property_value"],
    recommendedSources: ["Expertise", "Estimation notariale", "Données publiques DVF"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Acceptation d’un jeu de comparables faible, qui exige un motif écrit"],
  },
  {
    id: "property_track_rental",
    label: "Suivre la location",
    reason: "Distinguer le loyer facial du loyer réellement encaissé.",
    revealsFieldGroups: ["bail", "loyers", "vacance", "impayes", "depot_de_garantie"],
    unlocksKpis: ["property_gross_yield"],
    recommendedSources: ["Bail", "Quittances", "Relevé bancaire"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "property_compute_yield",
    label: "Calculer le rendement",
    reason:
      "Un rendement net exige que CHAQUE charge soit déclarée, même à zéro : une charge oubliée gonfle le rendement.",
    revealsFieldGroups: [
      "charges_recuperables",
      "charges_non_recuperables",
      "taxe_fonciere",
      "assurance",
      "gestion",
      "entretien",
    ],
    unlocksKpis: ["property_noi", "property_gross_yield"],
    recommendedSources: ["Avis de taxe foncière", "Contrats d’assurance", "Relevé de gérance"],
    dependsOn: ["property_track_rental"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: ["Distinction entre capex et réparation"],
  },
  {
    id: "property_measure_leverage",
    label: "Mesurer l’effet du crédit",
    reason: "Voir ce que le bien produit rapporté à ce que vous avez réellement investi.",
    revealsFieldGroups: ["dette_attribuee", "echeancier", "cash_investi"],
    unlocksKpis: ["property_ltv", "property_dscr", "property_equity"],
    recommendedSources: ["Contrat de prêt", "Échéancier bancaire"],
    dependsOn: ["loan_link_to_asset"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "property_prepare_sale",
    label: "Préparer une vente",
    reason: "Chiffrer le produit net réellement encaissé, frais et dette déduits.",
    revealsFieldGroups: ["valeur_de_sortie", "frais_de_cession", "date_de_vente", "dette_a_solder"],
    unlocksKpis: ["property_equity", "decision_option_comparison"],
    recommendedSources: ["Estimation", "Décompte anticipé"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Prix de sortie retenu", "Régime fiscal applicable à la cession"],
  },

  // ─── Carrière (section 26) ──────────────────────────────────────────────────────────
  {
    id: "career_understand_payslip",
    label: "Comprendre mon bulletin",
    reason: "Voir le passage du brut au net puis au cash réellement viré.",
    revealsFieldGroups: [
      "cotisations_salariales",
      "cotisations_patronales",
      "net_imposable",
      "temps_de_travail",
    ],
    unlocksKpis: ["gross_compensation", "net_cash_received"],
    recommendedSources: ["Bulletin de paie", "Contrat de travail"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "career_track_compensation",
    label: "Suivre ma rémunération",
    reason: "Mesurer l’évolution réelle, variable et primes comprises.",
    revealsFieldGroups: ["historique", "bonus", "participation", "avantages"],
    unlocksKpis: ["gross_compensation", "net_cash_received"],
    recommendedSources: ["Bulletins de paie", "Avenants"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "career_forecast_income",
    label: "Prévoir mes revenus",
    reason: "Alimenter la trésorerie prévisionnelle avec des flux contractuels, non des moyennes.",
    revealsFieldGroups: ["contrat", "recurrence", "dates_de_versement", "bonus_probable"],
    unlocksKpis: ["cash_runway", "upcoming_obligations_30d"],
    recommendedSources: ["Contrat de travail", "Avenant"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Probabilité d’un bonus, qui reste votre hypothèse"],
  },
  {
    id: "career_simulate_evolution",
    label: "Simuler une évolution",
    reason: "Comparer une promotion, une interruption ou un départ, sans toucher au réel.",
    revealsFieldGroups: ["croissance", "promotion", "interruption", "retraite"],
    unlocksKpis: ["scenario_trajectory"],
    recommendedSources: [],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Croissance salariale attendue"],
  },

  // ─── Entreprises (section 27) ───────────────────────────────────────────────────────
  {
    id: "business_estimate_value",
    label: "Estimer une valeur simple",
    reason:
      "Obtenir une fourchette à partir d’un multiple SOURCÉ ou d’une transaction, pas d’un chiffre de convenance.",
    revealsFieldGroups: ["methode", "multiple_source", "base_financiere"],
    unlocksKpis: ["business_equity_value", "business_attributable_value"],
    recommendedSources: ["Liasse fiscale", "Comptes annuels", "FEC", "Acte de transaction"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: [
      "Choix et source du multiple, qui n’est jamais auto-validé",
      "Comparabilité des transactions retenues",
    ],
  },
  {
    id: "business_understand_cash",
    label: "Comprendre le cash de la société",
    reason: "Voir la conversion de l’EBITDA en trésorerie, BFR et capex compris.",
    revealsFieldGroups: ["bfr", "variation_de_bfr", "capex", "impot_cash"],
    unlocksKpis: ["business_equity_value"],
    recommendedSources: ["FEC", "Comptes annuels", "Liasse fiscale"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Distinction capex de maintenance et capex de croissance"],
  },
  {
    id: "business_quality_of_earnings",
    label: "Faire une analyse de qualité des résultats",
    reason:
      "Un EBITDA normatif se construit retraitement par retraitement, chacun motivé et sourcé.",
    revealsFieldGroups: ["retraitements", "pont", "bfr_normatif", "mecanisme_de_prix"],
    unlocksKpis: ["business_equity_value"],
    recommendedSources: ["FEC", "Comptes annuels", "Contrats significatifs"],
    dependsOn: ["business_understand_cash"],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: [
      "Chaque retraitement de Quality of Earnings",
      "Qualification debt-like d’un élément de pont",
      "Séparation du standalone et des synergies",
    ],
  },
  {
    id: "business_track_personal_flows",
    label: "Suivre mes flux personnels",
    reason: "Savoir ce que la société vous a réellement versé, et à quelles dates.",
    revealsFieldGroups: ["dividendes", "compte_courant", "salaires", "cessions"],
    unlocksKpis: ["business_distributions"],
    recommendedSources: ["Décisions d’assemblée", "Relevé bancaire", "FEC"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "business_model_disposal",
    label: "Modéliser une cession",
    reason: "Chiffrer le produit net qui vous reviendrait, frais et fiscalité déduits.",
    revealsFieldGroups: ["mecanisme_de_prix", "reference", "leakage", "frais", "fiscalite"],
    unlocksKpis: ["decision_option_comparison", "business_attributable_value"],
    recommendedSources: ["Lettre d’intention", "Projet d’acte"],
    dependsOn: ["business_estimate_value"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: [
      "Préférences de liquidation entre classes de titres",
      "Position fiscale de la cession",
    ],
  },

  // ─── Fiscalité (section 28) ─────────────────────────────────────────────────────────
  {
    id: "tax_track_payments",
    label: "Suivre mes paiements",
    reason: "Tenir le solde de trésorerie fiscal, retenues et acomptes compris.",
    revealsFieldGroups: ["retenues", "acomptes", "paiements", "remboursements"],
    unlocksKpis: ["tax_paid"],
    recommendedSources: ["Avis d’imposition", "Bulletin de paie", "Relevé bancaire"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: [],
  },
  {
    id: "tax_estimate_liability",
    label: "Estimer mon impôt",
    reason:
      "Obtenir une estimation ou une fourchette, à partir de règles DÉCLARÉES et versionnées. Sans règle, aucun montant n’est produit.",
    revealsFieldGroups: ["revenus", "foyer_fiscal", "regles_datees", "deductions_et_credits"],
    unlocksKpis: ["tax_estimate"],
    recommendedSources: ["Avis d’imposition", "Déclaration", "Barème publié et daté"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: [
      "Position fiscale ambiguë",
      "Choix d’un régime d’imposition entre plusieurs options",
    ],
  },
  {
    id: "tax_compare_before_after",
    label: "Comparer avant et après impôt",
    reason: "Un rendement avant impôt et après impôt ne conduisent pas à la même décision.",
    revealsFieldGroups: ["flux_ou_actif_concerne", "regime", "horizon"],
    unlocksKpis: ["decision_option_comparison"],
    recommendedSources: ["Avis d’imposition", "Barème publié et daté"],
    dependsOn: ["tax_estimate_liability"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Régime applicable au flux considéré"],
  },

  // ─── Objectifs (section 29) ─────────────────────────────────────────────────────────
  {
    id: "goal_set_target",
    label: "Fixer un objectif chiffré",
    reason: "Rattacher un objectif à un indicateur mesurable de votre situation réelle.",
    revealsFieldGroups: ["type_dobjectif", "montant_cible", "echeance", "priorite"],
    unlocksKpis: ["goal_progress"],
    recommendedSources: [],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Priorité relative entre objectifs concurrents"],
  },
  {
    id: "goal_plan_effort",
    label: "Planifier l’effort nécessaire",
    reason: "Chiffrer le versement mensuel qui rendrait l’objectif atteignable.",
    revealsFieldGroups: ["contribution_prevue", "scenario_associe"],
    unlocksKpis: ["goal_monthly_effort", "scenario_trajectory"],
    recommendedSources: [],
    dependsOn: ["goal_set_target"],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Choix du scénario de projection"],
  },

  // ─── Scénarios (section 30) ─────────────────────────────────────────────────────────
  {
    id: "scenario_change_market",
    label: "Modifier mes hypothèses de marché",
    reason: "Voir l’effet d’un rendement, d’une volatilité ou d’une inflation différents.",
    revealsFieldGroups: ["rendement", "volatilite", "inflation"],
    unlocksKpis: ["scenario_trajectory"],
    recommendedSources: [],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Toutes les hypothèses de marché, qui restent les vôtres"],
  },
  {
    id: "scenario_add_events",
    label: "Ajouter des événements ponctuels",
    reason: "Placer une entrée ou une sortie datée dans la trajectoire.",
    revealsFieldGroups: ["libelle", "date", "montant", "sens"],
    unlocksKpis: ["scenario_trajectory"],
    recommendedSources: [],
    dependsOn: [],
    onDeactivate: "ASK_KEEP_OR_DELETE",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "SIMULATION",
    humanJudgementRemains: ["Probabilité de l’événement, qui n’est pas modélisée d’office"],
  },

  // ─── Sources (section 32) ───────────────────────────────────────────────────────────
  {
    id: "sources_connect_bank",
    label: "Connecter ou importer ma banque",
    reason: "Alimenter les flux sans ressaisie, en gardant la preuve de chaque opération.",
    revealsFieldGroups: ["connexion", "fichier_de_releve", "compte_cible"],
    unlocksKpis: ["observed_income", "essential_expenses", "source_freshness"],
    recommendedSources: ["Relevé bancaire CSV", "Connexion Open Banking en lecture"],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "OFFER_REVIEW",
    mode: "REAL",
    humanJudgementRemains: [
      "Acceptation d’une opération ressemblante : une ressemblance n’est pas un doublon",
    ],
  },
  {
    id: "sources_review_inbox",
    label: "Traiter ce qui demande une décision",
    reason: "Voir en un endroit ce qui manque, ce qui se contredit et ce qui a échoué.",
    revealsFieldGroups: [],
    unlocksKpis: ["pending_review_count", "source_freshness"],
    recommendedSources: [],
    dependsOn: [],
    onDeactivate: "KEEP_DATA_HIDE_SECTION",
    whenDataAlreadyPresent: "ACTIVATE_SILENTLY",
    mode: "REAL",
    humanJudgementRemains: ["Arbitrage de tout conflit de sources"],
  },
]);
