"use client";

import { useMemo, useState } from "react";
import {
  AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, BadgeEuro, BriefcaseBusiness, Building2, CalendarCheck,
  Check, ChevronRight, CircleDollarSign, Copy, Download, FileArchive, FilePlus2, FileText, Flag, FolderOpen, Gauge,
  Landmark, LineChart as LineChartIcon, LockKeyhole, Network, Plus, ReceiptText, Save, Scale, ShieldAlert, Sparkles,
  Target, TrendingUp, UploadCloud, WalletCards,
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ReferenceLine,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import type { Mutation } from "@/lib/data/contracts";
import { compareDebtVsInvest } from "@/lib/engine/decision";
import { amortizeLoan, deterministicProjection } from "@/lib/engine/financial";
import { underwriteRealEstate, type RealEstateInputs } from "@/lib/engine/real-estate";
import type { DashboardState, FinancialAccount, ProjectionResult, Scenario } from "@/lib/types";
import {
  Callout, Currency, DataBadge, EmptyState, MetricCard, Modal, Percent, ProgressBar, SectionHeader, type Explanation,
} from "@/components/ui";

type Mutate = (mutation: Mutation) => Promise<boolean>;

interface SectionProps {
  section: string;
  state: DashboardState;
  mutate: Mutate;
  busy: boolean;
  setExplanation: (explanation: Explanation) => void;
  projection: ProjectionResult | null;
  runProjection: (scenarioId: string, years?: number, simulations?: number, seed?: number) => Promise<ProjectionResult | null>;
  refresh: () => Promise<void>;
}

const chartCurrency = (value: number) => `${Math.round(value / 1000)} k€`;
const inputNumber = (value: string) => Number(value.replace(",", "."));

export function SectionContent(props: SectionProps) {
  switch (props.section) {
    case "net-worth": return <NetWorthPage {...props} />;
    case "cash-flow": return <CashFlowPage {...props} />;
    case "investments": return <InvestmentsPage {...props} />;
    case "debt": return <DebtPage {...props} />;
    case "real-estate": return <RealEstatePage {...props} />;
    case "career": return <CareerPage {...props} />;
    case "business-equity": return <BusinessPage {...props} />;
    case "tax": return <TaxPage {...props} />;
    case "scenarios": return <ScenariosPage {...props} />;
    case "decision-lab": return <DecisionLabPage {...props} />;
    case "goals": return <GoalsPage {...props} />;
    case "documents": return <DocumentsPage {...props} />;
    case "timeline": return <TimelinePage {...props} />;
    case "settings": return <SettingsPage {...props} />;
    default: return <TodayPage {...props} />;
  }
}

function TodayPage({ state, setExplanation, mutate, busy }: SectionProps) {
  const central = state.scenarios.find((scenario) => scenario.name === "Central") ?? state.scenarios[0];
  const projection = deterministicProjection(state.metrics.grossAssets, 12, central).map((point) => ({ year: 2026 + point.year, value: point.nominal, real: point.real }));
  const allocation = [
    { name: "Actions monde", value: state.positions.filter((position) => position.assetClass === "Actions monde").reduce((sum, position) => sum + position.value, 0), color: "#356b72" },
    { name: "Cash PEA", value: state.positions.filter((position) => position.isCash).reduce((sum, position) => sum + position.value, 0), color: "#89a7a2" },
    { name: "CTO non ventilé", value: state.positions.filter((position) => position.accountId === "acc_cto").reduce((sum, position) => sum + position.value, 0), color: "#c0a66a" },
    { name: "Cash bancaire", value: state.metrics.bankCash, color: "#dce5e2" },
  ].filter((item) => item.value > 0);
  const primaryGoal = state.goals[0];

  return <div className="page-stack">
    <SectionHeader eyebrow="Mercredi 19 août 2026" title="Bonjour Léo." description="Voici votre situation financière identifiée et ce qui mérite votre attention." actions={<button className="button primary" onClick={() => mutate({ action: "create_monthly_close", closeDate: state.asOfDate })} disabled={busy}><CalendarCheck size={16} />Clôturer le mois</button>} />
    <div className="uncertainty-strip"><DataBadge kind="ACTUAL" /><span>Valeurs observées</span><DataBadge kind="DERIVED" /><span>Calculs</span><DataBadge kind="MODEL_ASSUMPTION" /><span>Projections</span><span className="completeness"><strong>{Math.round(state.metrics.dataCompleteness * 100)} %</strong> des catégories de dépenses renseignées</span></div>
    <section className="metrics-grid four">
      <MetricCard label="Patrimoine net identifié" value={<Currency value={state.metrics.netWorth} />} tone="negative" detail={<><span className="negative-text">Sous zéro</span> · périmètre non exhaustif</>} onExplain={() => setExplanation(netWorthExplanation(state))} />
      <MetricCard label="Actifs bruts" value={<Currency value={state.metrics.grossAssets} />} detail={`${state.accounts.length} comptes consolidés`} onExplain={() => setExplanation(assetsExplanation(state))} />
      <MetricCard label="Cash disponible" value={<Currency value={state.metrics.bankCash} />} tone="warning" detail={<><span className="warning-text"><Currency value={state.metrics.emergencyCoverageMonths} /> mois</span> de loyer couvert</>} onExplain={() => setExplanation(liquidityExplanation(state))} />
      <MetricCard label="Cash flow mensuel connu" value={<Currency value={state.metrics.freeCashFlow} sign />} tone={state.metrics.freeCashFlow >= 0 ? "positive" : "negative"} detail="Avant échéance du prêt · dépenses incomplètes" onExplain={() => setExplanation(cashFlowExplanation(state))} />
    </section>
    <section className="dashboard-grid">
      <article className="panel chart-panel span-2">
        <div className="panel-header"><div><span className="eyebrow">Trajectoire centrale déterministe</span><h2>Patrimoine brut projeté</h2></div><div className="legend"><span><i className="legend-line nominal" />Nominal</span><span><i className="legend-line real" />Réel</span></div></div>
        <div className="hero-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={projection} margin={{ top: 10, right: 12, bottom: 0, left: 0 }}><defs><linearGradient id="areaNominal" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#39747a" stopOpacity={0.28} /><stop offset="95%" stopColor="#39747a" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border-soft)" /><XAxis dataKey="year" tickLine={false} axisLine={false} tick={{ fill: "var(--text-muted)", fontSize: 11 }} /><YAxis tickFormatter={chartCurrency} tickLine={false} axisLine={false} width={48} tick={{ fill: "var(--text-muted)", fontSize: 11 }} /><Tooltip formatter={(value) => [new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(Number(value)), ""]} /><Area type="monotone" dataKey="value" stroke="#39747a" strokeWidth={2.4} fill="url(#areaNominal)" /><Line type="monotone" dataKey="real" stroke="#9b8555" strokeDasharray="5 4" dot={false} /></AreaChart></ResponsiveContainer></div>
        <div className="chart-foot"><span>Hypothèse : <strong><Percent value={central.annualReturn} /></strong> de rendement, <strong><Currency value={central.monthlySavings} /></strong>/mois</span><a href="/scenarios">Tester les scénarios <ArrowRight size={14} /></a></div>
      </article>
      <article className="panel allocation-panel">
        <div className="panel-header"><div><span className="eyebrow">Allocation identifiée</span><h2>Où sont les actifs</h2></div></div>
        <div className="allocation-content"><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={allocation} dataKey="value" nameKey="name" innerRadius={55} outerRadius={76} paddingAngle={2} stroke="none">{allocation.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie></PieChart></ResponsiveContainer><div className="donut-center"><strong><Currency value={state.metrics.grossAssets} compact /></strong><span>actifs</span></div></div><div className="allocation-legend">{allocation.map((item) => <div key={item.name}><span><i style={{ background: item.color }} />{item.name}</span><strong><Percent value={item.value / state.metrics.grossAssets} /></strong></div>)}</div></div>
      </article>
      <article className="panel cashflow-card">
        <div className="panel-header"><div><span className="eyebrow">Cash flow connu</span><h2>Ce mois-ci</h2></div><a href="/cash-flow">Détails <ChevronRight size={14} /></a></div>
        <div className="flow-rows"><div><span><i className="flow-dot income" />Revenus actifs</span><strong><Currency value={state.metrics.monthlyIncome} /></strong></div><div><span><i className="flow-dot expense" />Dépenses renseignées</span><strong>−<Currency value={state.metrics.monthlyExpenses} /></strong></div><div><span><i className="flow-dot debt" />Dette dès déc. 2026</span><strong>−<Currency value={state.liabilities.reduce((sum, item) => sum + item.monthlyPayment, 0)} /></strong></div></div>
        <div className="flow-total"><span>Disponible avant prêt</span><strong><Currency value={state.metrics.freeCashFlow} sign /></strong></div>
      </article>
      <article className="panel goals-card">
        <div className="panel-header"><div><span className="eyebrow">Objectif prioritaire</span><h2>{primaryGoal?.name ?? "Aucun objectif"}</h2></div><a href="/goals">Gérer <ChevronRight size={14} /></a></div>
        {primaryGoal ? <><div className="goal-number"><Currency value={Math.max(0, state.metrics.netWorth)} /><span>sur <Currency value={primaryGoal.targetAmount} /></span></div><ProgressBar value={Math.max(0, state.metrics.netWorth) / primaryGoal.targetAmount} /><p className="muted-copy">Le patrimoine net est négatif ; le premier jalon est le retour à zéro.</p></> : null}
      </article>
      <article className="panel alerts-panel span-2">
        <div className="panel-header"><div><span className="eyebrow">Risques & attention</span><h2>{state.alerts.length} points ouverts</h2></div><span className="alert-count">{state.alerts.filter((alert) => alert.severity === "HIGH").length} critiques</span></div>
        <div className="alert-list">{state.alerts.map((alert) => <div className="alert-row" key={alert.id}><span className={`severity-icon ${alert.severity.toLowerCase()}`}><AlertTriangle size={15} /></span><div><strong>{alert.title}</strong><p>{alert.detail}</p></div><span className={`severity-label ${alert.severity.toLowerCase()}`}>{alert.severity === "HIGH" ? "Prioritaire" : "À vérifier"}</span></div>)}</div>
      </article>
      <article className="panel event-panel">
        <div className="panel-header"><div><span className="eyebrow">Prochain événement majeur</span><h2>Prêt étudiant</h2></div><Flag size={18} /></div><div className="event-date"><strong>05</strong><span>DÉC<br />2026</span></div><p>Première échéance annoncée de <strong><Currency value={284.72} /></strong>.</p><div className="event-foot"><span>Dans 108 jours à la date zéro</span><a href="/debt">Voir l’échéancier</a></div>
      </article>
    </section>
  </div>;
}

function NetWorthPage({ state, mutate, busy, setExplanation }: SectionProps) {
  const [modal, setModal] = useState<"add" | "edit" | null>(null);
  const [selected, setSelected] = useState<FinancialAccount | null>(null);
  const [form, setForm] = useState({ institution: "", name: "", accountType: "BANK" as FinancialAccount["type"], balance: "", currency: "EUR", date: state.asOfDate });
  const bank = state.accounts.filter((item) => item.type === "BANK" || item.type === "SAVINGS");
  const investments = state.accounts.filter((item) => item.type === "PEA" || item.type === "CTO");
  async function save(event: React.FormEvent) {
    event.preventDefault();
    const ok = selected ? await mutate({ action: "update_account", accountId: selected.id, balance: inputNumber(form.balance), balanceDate: form.date }) : await mutate({ action: "add_account", institution: form.institution, name: form.name, accountType: form.accountType, balance: inputNumber(form.balance), currency: form.currency.toUpperCase() });
    if (ok) { setModal(null); setSelected(null); }
  }
  function edit(account: FinancialAccount) { setSelected(account); setForm({ institution: account.institution, name: account.name, accountType: account.type, balance: String(account.balance), currency: account.currency, date: state.asOfDate }); setModal("edit"); }
  return <div className="page-stack"><SectionHeader eyebrow="Balance sheet" title="Net Worth" description="Un bilan consolidé sans double comptage. Les positions expliquent les comptes d’investissement, elles ne s’y ajoutent pas." actions={<button className="button primary" onClick={() => { setSelected(null); setForm({ institution: "", name: "", accountType: "BANK", balance: "", currency: "EUR", date: state.asOfDate }); setModal("add"); }}><Plus size={16} />Ajouter un compte</button>} />
    <section className="metrics-grid four"><MetricCard label="Patrimoine brut" value={<Currency value={state.metrics.grossAssets} />} onExplain={() => setExplanation(assetsExplanation(state))} /><MetricCard label="Dettes" value={<Currency value={state.metrics.debt} />} tone="negative" /><MetricCard label="Patrimoine net identifié" value={<Currency value={state.metrics.netWorth} />} tone="negative" onExplain={() => setExplanation(netWorthExplanation(state))} /><MetricCard label="Patrimoine investi" value={<Currency value={state.metrics.investedAssets} />} /></section>
    <Callout title="Périmètre identifié">Ce bilan inclut uniquement les actifs et dettes déclarés. Il ne prétend pas représenter un patrimoine économique exhaustif.</Callout>
    <section className="two-column"><AccountTable title="Cash bancaire" accounts={bank} onEdit={edit} /><AccountTable title="Investissements" accounts={investments} onEdit={edit} /></section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Passif</span><h2>Dettes identifiées</h2></div></div>{state.liabilities.map((liability) => <div className="account-row" key={liability.id}><span className="account-logo debt-logo"><Landmark size={17} /></span><div className="account-main"><strong>{liability.name}</strong><span>{liability.lender} · {liability.annualRate === 0 ? "Taux 0 %" : <Percent value={liability.annualRate} />}</span></div><DataBadge kind={liability.provenance.kind} /><strong className="account-balance negative-text">−<Currency value={liability.currentBalance} /></strong></div>)}</section>
    <Modal open={Boolean(modal)} onClose={() => setModal(null)} title={selected ? `Mettre à jour ${selected.name}` : "Ajouter un compte"} subtitle="Toute nouvelle valeur conserve un historique daté"><form className="form-grid" onSubmit={save}>{!selected ? <><label>Institution<input className="text-input" value={form.institution} onChange={(event) => setForm({ ...form, institution: event.target.value })} required /></label><label>Nom du compte<input className="text-input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Type<select className="text-input" value={form.accountType} onChange={(event) => setForm({ ...form, accountType: event.target.value as FinancialAccount["type"] })}><option value="BANK">Compte bancaire</option><option value="SAVINGS">Épargne</option><option value="PEA">PEA</option><option value="CTO">CTO</option><option value="OTHER">Autre</option></select></label><label>Devise<input className="text-input" maxLength={3} value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value })} required /></label></> : null}<label>Solde<input className="text-input" type="number" step="0.01" value={form.balance} onChange={(event) => setForm({ ...form, balance: event.target.value })} required /></label>{selected ? <label>Date du solde<input className="text-input" type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required /></label> : null}<div className="form-actions"><button type="button" className="button secondary" onClick={() => setModal(null)}>Annuler</button><button className="button primary" disabled={busy}><Save size={15} />Enregistrer</button></div></form></Modal>
  </div>;
}

function AccountTable({ title, accounts, onEdit }: { title: string; accounts: FinancialAccount[]; onEdit: (account: FinancialAccount) => void }) {
  return <article className="panel"><div className="panel-header"><div><span className="eyebrow">Actifs</span><h2>{title}</h2></div><strong><Currency value={accounts.reduce((sum, item) => sum + item.balance, 0)} /></strong></div><div className="account-list">{accounts.map((account) => <button className="account-row account-button" key={account.id} onClick={() => onEdit(account)}><span className="account-logo">{account.institution.slice(0, 2).toUpperCase()}</span><div className="account-main"><strong>{account.name}</strong><span>{account.institution} · {account.currency}</span></div><DataBadge kind={account.provenance.kind} /><strong className={`account-balance ${account.balance < 0 ? "negative-text" : ""}`}><Currency value={account.balance} /></strong><ChevronRight size={15} /></button>)}</div></article>;
}

function CashFlowPage({ state, mutate, busy, setExplanation }: SectionProps) {
  const [modal, setModal] = useState(false);
  const [form, setForm] = useState({ accountId: state.accounts[0]?.id ?? "", categoryId: "exp_groceries", date: state.asOfDate, label: "", amount: "", updateBalance: true });
  const chart = ["Mars", "Avr.", "Mai", "Juin", "Juil.", "Août"].map((month, index) => ({ month, income: index === 5 ? state.metrics.monthlyIncome : 0, expense: index === 5 ? state.metrics.monthlyExpenses : 0 }));
  async function addTransaction(event: React.FormEvent) { event.preventDefault(); const ok = await mutate({ action: "add_transaction", accountId: form.accountId, categoryId: form.categoryId, date: form.date, label: form.label, amount: inputNumber(form.amount), updateBalance: form.updateBalance }); if (ok) { setModal(false); setForm({ ...form, label: "", amount: "" }); } }
  return <div className="page-stack"><SectionHeader eyebrow="Income & spending" title="Cash Flow" description="Les ratios restent provisoires tant que les catégories manquantes ne sont pas renseignées." actions={<button className="button primary" onClick={() => setModal(true)}><Plus size={16} />Ajouter une transaction</button>} />
    <section className="metrics-grid four"><MetricCard label="Revenus actifs" value={<Currency value={state.metrics.monthlyIncome} />} /><MetricCard label="Dépenses connues" value={<Currency value={state.metrics.monthlyExpenses} />} /><MetricCard label="Free cash flow connu" value={<Currency value={state.metrics.freeCashFlow} sign />} tone={state.metrics.freeCashFlow >= 0 ? "positive" : "negative"} onExplain={() => setExplanation(cashFlowExplanation(state))} /><MetricCard label="Taux d’épargne provisoire" value={<Percent value={state.metrics.savingsRate} />} tone={state.metrics.savingsRate < 0 ? "negative" : "neutral"} /></section>
    <Callout tone="warning" title="Données partielles">{state.expenseCategories.filter((category) => category.monthlyAmount === null).length} catégories n’ont encore aucun montant. Aucun montant arbitraire n’est substitué.</Callout>
    <section className="two-column wide-left"><article className="panel chart-panel"><div className="panel-header"><div><span className="eyebrow">Historique observé</span><h2>Revenus et dépenses</h2></div></div><div className="medium-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid vertical={false} stroke="var(--border-soft)" /><XAxis dataKey="month" axisLine={false} tickLine={false} /><YAxis tickFormatter={chartCurrency} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="income" name="Revenus" fill="#39747a" radius={[4, 4, 0, 0]} /><Bar dataKey="expense" name="Dépenses" fill="#c6a765" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div><p className="muted-copy">Les mois sans données sont affichés à zéro, et non estimés.</p></article><article className="panel"><div className="panel-header"><div><span className="eyebrow">Futur proche</span><h2>Événements 365 jours</h2></div></div><div className="timeline-mini"><div><i /><span><strong>5 déc. 2026</strong><small>Première mensualité étudiant</small></span><b>−284,72 €</b></div><div className="muted"><i /><span><strong>À dater</strong><small>Revenu professeur de tennis</small></span><b>+130 €</b></div><div className="muted"><i /><span><strong>À confirmer</strong><small>CAF</small></span><b>—</b></div></div></article></section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Budget confortable</span><h2>Catégories mensuelles</h2></div><span className="panel-note">Cliquez pour renseigner</span></div><div className="category-grid">{state.expenseCategories.filter((category) => category.groupName !== "Revenus" && category.groupName !== "Épargne").map((category) => <label className="category-item" key={category.id}><span><strong>{category.name}</strong><small>{category.groupName} · {category.essential ? "Essentielle" : "Discrétionnaire"}</small></span><div className="inline-amount"><input type="number" min="0" step="1" placeholder="—" defaultValue={category.monthlyAmount ?? ""} onBlur={(event) => { const next = event.target.value === "" ? null : inputNumber(event.target.value); if (next !== category.monthlyAmount) void mutate({ action: "update_expense", categoryId: category.id, monthlyAmount: next }); }} /><span>€/mois</span></div><DataBadge kind={category.provenance.kind} /></label>)}</div></section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Ledger</span><h2>Transactions récentes</h2></div></div>{state.transactions.length ? <div className="simple-table"><div className="table-head"><span>Date</span><span>Libellé</span><span>Catégorie</span><span>Compte</span><span>Montant</span></div>{state.transactions.map((transaction) => <div className="table-row" key={transaction.id}><span>{new Date(transaction.date).toLocaleDateString("fr-FR")}</span><strong>{transaction.label}</strong><span>{transaction.categoryName}</span><span>{transaction.accountName}</span><strong className={transaction.amount < 0 ? "negative-text" : "positive-text"}><Currency value={transaction.amount} sign /></strong></div>)}</div> : <EmptyState title="Aucune transaction importée" detail="Ajoutez une première transaction manuelle ou importez un CSV dans une prochaine itération." action={<button className="button secondary" onClick={() => setModal(true)}>Ajouter la première</button>} />}</section>
    <Modal open={modal} onClose={() => setModal(false)} title="Ajouter une transaction" subtitle="Une correction manuelle reste prioritaire sur toute future synchronisation"><form className="form-grid" onSubmit={addTransaction}><label>Compte<select className="text-input" value={form.accountId} onChange={(event) => setForm({ ...form, accountId: event.target.value })}>{state.accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Date<input className="text-input" type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required /></label><label className="full">Libellé<input className="text-input" value={form.label} onChange={(event) => setForm({ ...form, label: event.target.value })} required /></label><label>Catégorie<select className="text-input" value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })}>{state.expenseCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Montant signé<input className="text-input" type="number" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} placeholder="-45,20" required /></label><label className="checkbox-row full"><input type="checkbox" checked={form.updateBalance} onChange={(event) => setForm({ ...form, updateBalance: event.target.checked })} />Répercuter ce mouvement sur le solde du compte</label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setModal(false)}>Annuler</button><button className="button primary" disabled={busy}>Enregistrer</button></div></form></Modal>
  </div>;
}

function InvestmentsPage({ state, setExplanation }: SectionProps) {
  const pea = state.accounts.find((account) => account.id === "acc_pea");
  const cto = state.accounts.find((account) => account.id === "acc_cto");
  const peaPositions = state.positions.filter((position) => position.accountId === "acc_pea");
  const peaComponents = peaPositions.reduce((sum, position) => sum + position.value, 0);
  const peaGap = (pea?.balance ?? 0) - peaComponents;
  return <div className="page-stack"><SectionHeader eyebrow="Portfolio" title="Investments" description="Positions, allocation, performance connue et contrôles de réconciliation." actions={<button className="button secondary"><UploadCloud size={15} />Import CSV <span className="soon">V1.1</span></button>} />
    <section className="metrics-grid four"><MetricCard label="Actifs investis" value={<Currency value={state.metrics.investedAssets} />} /><MetricCard label="Cash PEA" value={<Currency value={state.positions.filter((position) => position.isCash).reduce((sum, position) => sum + position.value, 0)} />} /><MetricCard label="Plus-value PEA annoncée" value={<Currency value={703.12} sign />} tone="positive" detail="Réconciliation à 0,01 € près" /><MetricCard label="Concentration MSCI World" value={<Percent value={8698 / state.metrics.grossAssets} />} detail="Part des actifs bruts identifiés" /></section>
    <section className="two-column"><article className="panel account-summary"><div className="account-hero"><span className="account-logo large">BB</span><div><span className="eyebrow">Boursobank</span><h2>PEA</h2></div><strong><Currency value={pea?.balance ?? 0} /></strong></div><div className="account-stats"><div><span>Versements annoncés</span><strong><Currency value={14300} /></strong></div><div><span>Gain annoncé</span><strong className="positive-text"><Currency value={703.12} sign /></strong></div><div><span>Composantes</span><strong><Currency value={peaComponents} /></strong></div></div></article><article className="panel account-summary"><div className="account-hero"><span className="account-logo large">TR</span><div><span className="eyebrow">Trade Republic</span><h2>CTO</h2></div><strong><Currency value={cto?.balance ?? 0} /></strong></div><div className="account-stats"><div><span>Performance affichée</span><strong className="positive-text">+77,71 %</strong></div><div><span>Ventilation</span><strong className="warning-text">Manquante</strong></div><div><span>Devise reporting</span><strong>EUR</strong></div></div></article></section>
    {Math.abs(peaGap) > 0.01 ? <Callout tone="warning" title="Réconciliation PEA ouverte">Le total du compte dépasse les positions de <Currency value={peaGap} />. Le total déclaré reste la valeur comptable, sans créer de position fictive.</Callout> : null}
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Positions observées</span><h2>Portefeuille consolidé</h2></div><button className="link-button" onClick={() => setExplanation({ title: "Réconciliation des investissements", formula: "Total du compte − Σ valeur des positions", inputs: [{ label: "Total PEA", value: "15 003,13 €", kind: "ACTUAL", date: state.asOfDate }, { label: "ETF", value: "8 698,00 €", kind: "ACTUAL", date: state.asOfDate }, { label: "Cash PEA", value: "6 304,57 €", kind: "ACTUAL", date: state.asOfDate }], note: "Le cash PEA est une position interne au PEA et n’est jamais ajouté au cash bancaire." })}>Explain calculation</button></div><div className="holdings-table"><div className="table-head"><span>Position</span><span>Compte</span><span>Classe</span><span>Coût connu</span><span>Valeur</span><span>Statut</span></div>{state.positions.map((position) => <div className="table-row" key={position.id}><span className="holding-name"><i>{position.securityName.slice(0, 2).toUpperCase()}</i><span><strong>{position.securityName}</strong><small>{position.ticker ?? position.currency}</small></span></span><span>{state.accounts.find((account) => account.id === position.accountId)?.name}</span><span>{position.assetClass}</span><span>{position.costBasis === undefined ? "—" : <Currency value={position.costBasis} />}</span><strong><Currency value={position.value} /></strong><DataBadge kind={position.provenance.kind} /></div>)}</div></section>
    <Callout title="Limite des métriques de risque">Volatilité, drawdown, Sharpe et corrélations ne sont pas affichés sans historique de prix fiable. Ils ne préjugeront jamais des performances futures.</Callout>
  </div>;
}

function DebtPage({ state, setExplanation }: SectionProps) {
  const loan = state.liabilities[0];
  const schedule = amortizeLoan(loan.principal, loan.annualRate, loan.paymentCount, loan.monthlyPayment);
  const contractualTotal = loan.monthlyPayment * loan.paymentCount;
  const [investmentReturn, setInvestmentReturn] = useState(5.5);
  const comparison = compareDebtVsInvest({ availableCash: 5000, debtBalance: loan.currentBalance, debtRate: loan.annualRate, investmentReturn: investmentReturn / 100, volatility: 0.15, inflation: 0.02, years: 5, liquidityWeight: 0.03 });
  return <div className="page-stack"><SectionHeader eyebrow="Liabilities" title="Debt" description="Échéanciers, coût du crédit et arbitrage remboursement vs investissement." actions={<button className="button secondary"><FilePlus2 size={15} />Importer l’échéancier <span className="soon">À connecter</span></button>} />
    <section className="metrics-grid four"><MetricCard label="Capital annoncé" value={<Currency value={loan.currentBalance} />} /><MetricCard label="Taux" value={<Percent value={loan.annualRate} />} tone="positive" /><MetricCard label="Mensualité annoncée" value={<Currency value={loan.monthlyPayment} />} /><MetricCard label="Écart contractuel" value={<Currency value={contractualTotal - loan.principal} />} tone="warning" onExplain={() => setExplanation({ title: "Écart du prêt étudiant", formula: "Mensualité × nombre d’échéances − capital annoncé", inputs: [{ label: "Mensualité", value: "284,72 €", kind: "ACTUAL", date: state.asOfDate }, { label: "Échéances", value: "60", kind: "ACTUAL", date: state.asOfDate }, { label: "Capital", value: "16 745,00 €", kind: "ACTUAL", date: state.asOfDate }], note: "17 083,20 € − 16 745,00 € = 338,20 €. Aucune explication n’est supposée." })} /></section>
    <Callout tone="warning" title="Échéancier non réconcilié">284,72 € × 60 = <Currency value={contractualTotal} />, soit <Currency value={contractualTotal - loan.principal} /> au-dessus du capital annoncé. Le tableau arrête le principal à zéro ; seul le document bancaire pourra expliquer le reliquat contractuel.</Callout>
    <section className="two-column wide-left"><article className="panel"><div className="panel-header"><div><span className="eyebrow">Amortissement dérivé</span><h2>Solde restant</h2></div><button className="link-button" onClick={() => setExplanation({ title: "Amortissement à 0 %", formula: "Principal payé = min(solde, mensualité) ; intérêts = 0", inputs: [{ label: "Capital", value: "16 745 €", kind: "ACTUAL" }, { label: "Taux", value: "0 %", kind: "ACTUAL" }, { label: "Mensualité", value: "284,72 €", kind: "ACTUAL" }], note: "La dernière ligne dérivée est plafonnée au solde restant et ne remplace pas l’échéancier contractuel." })}>Explain calculation</button></div><div className="medium-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={schedule.filter((_, index) => index % 6 === 0).map((row) => ({ month: row.paymentNumber, balance: row.closingBalance }))}><defs><linearGradient id="debtArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ab5a4e" stopOpacity={0.25} /><stop offset="1" stopColor="#ab5a4e" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border-soft)" /><XAxis dataKey="month" axisLine={false} tickLine={false} /><YAxis tickFormatter={chartCurrency} axisLine={false} tickLine={false} /><Tooltip /><Area dataKey="balance" stroke="#ab5a4e" fill="url(#debtArea)" /></AreaChart></ResponsiveContainer></div></article><article className="panel loan-facts"><div className="panel-header"><div><span className="eyebrow">Contrat annoncé</span><h2>Dates clés</h2></div></div><dl><div><dt>Première échéance</dt><dd>5 décembre 2026</dd></div><div><dt>Dernière échéance prévue</dt><dd>5 novembre 2031</dd></div><div><dt>Nombre annoncé</dt><dd>60 mensualités</dd></div><div><dt>Coût d’intérêt dérivé</dt><dd>0,00 €</dd></div></dl></article></section>
    <section className="panel decision-preview"><div className="panel-header"><div><span className="eyebrow">Arbitrage</span><h2>Rembourser à 0 % ou investir</h2></div><a href="/decision-lab">Ouvrir le Decision Lab <ArrowRight size={14} /></a></div><div className="decision-controls"><label>Rendement annuel hypothétique <strong>{investmentReturn.toFixed(1)} %</strong><input type="range" min="0" max="10" step="0.1" value={investmentReturn} onChange={(event) => setInvestmentReturn(Number(event.target.value))} /></label></div><div className="comparison-cards"><div><span>Rembourser 5 000 €</span><strong><Currency value={comparison.repay.nominalBenefit} /></strong><small>Bénéfice certain : 0 € d’intérêt évité</small></div><div className="preferred"><span>Investir 5 000 €</span><strong><Currency value={comparison.invest.nominalBenefit} /></strong><small>Valeur espérée, non garantie</small></div></div><Callout title="Lecture">{comparison.conclusion} La priorité reste néanmoins la constitution d’une réserve de liquidité.</Callout></section>
  </div>;
}

const defaultProperty: RealEstateInputs = { purchasePrice: 220000, acquisitionCosts: 17600, renovation: 15000, furniture: 5000, downPayment: 30000, loanAmount: 227600, annualRate: 0.035, loanYears: 25, monthlyRent: 1100, vacancyRate: 0.05, annualOperatingCosts: 3200, annualPropertyGrowth: 0.015, rentGrowth: 0.015, holdingYears: 10, sellingCostsRate: 0.06, taxRate: 0.3 };

function RealEstatePage({ setExplanation }: SectionProps) {
  const [inputs, setInputs] = useState(defaultProperty);
  const result = useMemo(() => underwriteRealEstate(inputs), [inputs]);
  function field(key: keyof RealEstateInputs, label: string, suffix: string, step = "1") { const display = key.toLowerCase().includes("rate") || key === "vacancyRate" || key === "annualPropertyGrowth" || key === "rentGrowth" || key === "taxRate" ? Number(inputs[key]) * 100 : inputs[key]; return <label>{label}<div className="suffix-input"><input type="number" step={step} value={display} onChange={(event) => { const raw = Number(event.target.value); const value = key.toLowerCase().includes("rate") || key === "vacancyRate" || key === "annualPropertyGrowth" || key === "rentGrowth" || key === "taxRate" ? raw / 100 : raw; setInputs({ ...inputs, [key]: value }); }} /><span>{suffix}</span></div></label>; }
  return <div className="page-stack"><SectionHeader eyebrow="Underwriting" title="Real Estate" description="Étude d’un actif locatif avec dette, vacance, fiscalité, sortie et métriques d’equity." actions={<button className="button secondary"><Save size={15} />Sauvegarder l’étude <span className="soon">V1.1</span></button>} />
    <Callout title="Cas de travail non patrimonial">Cette étude n’ajoute rien au patrimoine actuel tant qu’un achat réel n’est pas enregistré. Toutes les valeurs ci-dessous sont des hypothèses modifiables.</Callout>
    <section className="underwriting-layout"><article className="panel input-panel"><div className="panel-header"><div><span className="eyebrow">Hypothèses</span><h2>Projet locatif</h2></div><DataBadge kind="USER_ASSUMPTION" /></div><div className="input-sections"><h3>Acquisition</h3><div className="mini-form-grid">{field("purchasePrice", "Prix d’achat", "€")}{field("acquisitionCosts", "Frais d’acquisition", "€")}{field("renovation", "Travaux", "€")}{field("furniture", "Mobilier", "€")}</div><h3>Financement</h3><div className="mini-form-grid">{field("downPayment", "Apport", "€")}{field("loanAmount", "Crédit", "€")}{field("annualRate", "Taux nominal", "%", "0.01")}{field("loanYears", "Durée", "ans")}</div><h3>Exploitation & sortie</h3><div className="mini-form-grid">{field("monthlyRent", "Loyer mensuel", "€")}{field("vacancyRate", "Vacance", "%", "0.1")}{field("annualOperatingCosts", "Charges annuelles", "€")}{field("taxRate", "Taux fiscal effectif", "%", "0.1")}{field("annualPropertyGrowth", "Croissance valeur", "%", "0.1")}{field("holdingYears", "Horizon", "ans")}</div></div></article>
      <div className="results-stack"><section className="metrics-grid two"><MetricCard label="TRI equity" value={result.irr === null ? "N/A" : <Percent value={result.irr} />} tone={result.irr !== null && result.irr > 0.06 ? "positive" : "neutral"} onExplain={() => setExplanation({ title: "TRI immobilier", formula: "Taux r tel que Σ CFₜ / (1+r)ᵗ = 0", inputs: [{ label: "Equity initiale", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(-result.cashFlows[0]), kind: "USER_ASSUMPTION" }, { label: "Cash flows annuels", value: `${result.cashFlows.length - 1} années`, kind: "DERIVED" }, { label: "Produit de cession net", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(result.cashFlows.at(-1) ?? 0), kind: "DERIVED" }], note: "Le TRI dépend fortement du prix de sortie, de la fiscalité simplifiée et de la vacance." })} /><MetricCard label="VAN à 6 %" value={<Currency value={result.npv} />} tone={result.npv >= 0 ? "positive" : "negative"} /><MetricCard label="MOIC" value={`${result.moic.toFixed(2)}×`} /><MetricCard label="Cash flow annuel" value={<Currency value={result.annualCashFlow} sign />} tone={result.annualCashFlow >= 0 ? "positive" : "negative"} /></section><article className="panel result-summary"><div className="panel-header"><div><span className="eyebrow">Résultat</span><h2>Économie du projet</h2></div></div><dl><div><dt>Coût total projet</dt><dd><Currency value={result.totalProjectCost} /></dd></div><div><dt>Mensualité hors assurance</dt><dd><Currency value={result.monthlyPayment} /></dd></div><div><dt>Rendement brut</dt><dd><Percent value={result.grossYield} /></dd></div><div><dt>Rendement net d’exploitation</dt><dd><Percent value={result.netYield} /></dd></div><div><dt>Cash-on-cash initial</dt><dd><Percent value={result.cashOnCash} /></dd></div><div><dt>LTV</dt><dd><Percent value={result.ltv} /></dd></div><div><dt>DSCR</dt><dd>{Number.isFinite(result.dscr) ? `${result.dscr.toFixed(2)}×` : "Sans dette"}</dd></div><div><dt>Intérêts totaux</dt><dd><Currency value={result.totalInterest} /></dd></div><div><dt>Valeur de sortie brute</dt><dd><Currency value={result.exitValue} /></dd></div></dl></article><Callout tone={result.annualCashFlow < 0 ? "warning" : "success"} title={result.annualCashFlow < 0 ? "Effort d’épargne requis" : "Cash flow positif"}>{result.annualCashFlow < 0 ? <>Le projet consomme <Currency value={-result.annualCashFlow / 12} /> par mois avant aléas et CAPEX exceptionnels.</> : <>Le projet génère <Currency value={result.annualCashFlow / 12} /> par mois sous les hypothèses.</>}</Callout></div>
    </section>
  </div>;
}

function CareerPage({ state }: SectionProps) {
  const [track, setTrack] = useState("M&A → PE");
  const tracks = [
    { name: "M&A long terme", base: 42, growth: 0.12, bonus: 9 }, { name: "M&A → PE", base: 42, growth: 0.16, bonus: 9 },
    { name: "Corporate Development", base: 40, growth: 0.08, bonus: 6 }, { name: "Transaction Services", base: 40, growth: 0.09, bonus: 7 },
    { name: "Startup / scale-up", base: 38, growth: 0.1, bonus: 4 }, { name: "Entrepreneuriat", base: 20, growth: 0.28, bonus: 0 },
  ];
  const selected = tracks.find((item) => item.name === track) ?? tracks[0];
  const salaryData = Array.from({ length: 9 }, (_, year) => ({ year: 2027 + year, fixed: selected.base * Math.pow(1 + selected.growth, year), variable: selected.bonus * Math.pow(1.08, year), total: selected.base * Math.pow(1 + selected.growth, year) + selected.bonus * Math.pow(1.08, year) }));
  const variableAssumption = state.assumptions.find((assumption) => assumption.id === "asm_variable");
  return <div className="page-stack"><SectionHeader eyebrow="Human capital" title="Career" description="Trajectoires de rémunération séparées du patrimoine observé. Les courbes sont des hypothèses, pas des promesses." />
    <section className="metrics-grid four"><MetricCard label="Fixe central premier CDI" value={<Currency value={42000} />} detail="Brut annuel" /><MetricCard label="Variable central" value={<Currency value={Number(variableAssumption?.value ?? 9000)} />} detail="Hypothèse faible confiance" tone="warning" /><MetricCard label="Revenu actuel net" value={<Currency value={state.metrics.monthlyIncome} />} detail="Mensuel" /><MetricCard label="Horizon M&A avant tentative PE" value="≈ 2 ans" detail="Scénario, non certitude" /></section>
    <Callout tone="warning" title="Courbes non sourcées en V1">Les valeurs ci-dessous sont des hypothèses de travail internes datées du 19 août 2026. Elles doivent être remplacées par des benchmarks externes vérifiés.</Callout>
    <section className="career-layout"><article className="panel track-list"><div className="panel-header"><div><span className="eyebrow">Branches</span><h2>Trajectoire testée</h2></div></div>{tracks.map((item) => <button key={item.name} className={track === item.name ? "active" : ""} onClick={() => setTrack(item.name)}><span><strong>{item.name}</strong><small>Croissance modèle {Math.round(item.growth * 100)} %/an</small></span><ChevronRight size={16} /></button>)}</article><article className="panel chart-panel"><div className="panel-header"><div><span className="eyebrow">Rémunération brute hypothétique</span><h2>{track}</h2></div><DataBadge kind="MODEL_ASSUMPTION" /></div><div className="medium-chart tall"><ResponsiveContainer width="100%" height="100%"><AreaChart data={salaryData}><defs><linearGradient id="salaryArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#39747a" stopOpacity={0.25} /><stop offset="1" stopColor="#39747a" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border-soft)" /><XAxis dataKey="year" axisLine={false} tickLine={false} /><YAxis tickFormatter={(value) => `${value} k€`} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => `${Number(value).toFixed(1)} k€`} /><Area type="monotone" dataKey="total" name="Total" stroke="#39747a" fill="url(#salaryArea)" /><Line type="monotone" dataKey="fixed" name="Fixe" stroke="#9b8555" dot={false} /></AreaChart></ResponsiveContainer></div></article></section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Premier CDI</span><h2>Fourchettes initiales</h2></div></div><div className="salary-bands"><div><span>Minimum</span><strong>40 k€ fixe</strong><small>+ 3 k€ variable</small></div><div className="central"><span>Central</span><strong>42 k€ fixe</strong><small>+ 9 k€ variable hypothétique</small></div><div><span>Maximum</span><strong>45 k€ fixe</strong><small>+ 15 k€ variable</small></div></div></section>
  </div>;
}

function BusinessPage({}: SectionProps) {
  const [revenue, setRevenue] = useState(500000);
  const [ebitda, setEbitda] = useState(80000);
  const [multiple, setMultiple] = useState(6);
  const [debt, setDebt] = useState(100000);
  const [cash, setCash] = useState(30000);
  const [ownership, setOwnership] = useState(100);
  const enterpriseValue = ebitda * multiple;
  const equityValue = enterpriseValue - debt + cash;
  const attributable = equityValue * ownership / 100;
  return <div className="page-stack"><SectionHeader eyebrow="Private assets" title="Business Equity" description="Bac à sable de valorisation ; aucune participation entrepreneuriale n’est actuellement déclarée." actions={<button className="button secondary"><Plus size={15} />Ajouter une société <span className="soon">V1.1</span></button>} />
    <Callout title="Aucun actif business actuel">Les calculs ci-dessous restent isolés du patrimoine tant qu’une participation réelle n’est pas enregistrée.</Callout>
    <section className="business-layout"><article className="panel input-panel"><div className="panel-header"><div><span className="eyebrow">Multiple EBITDA</span><h2>Valorisation sandbox</h2></div><DataBadge kind="USER_ASSUMPTION" /></div><div className="mini-form-grid business-form"><label>Chiffre d’affaires<div className="suffix-input"><input type="number" value={revenue} onChange={(event) => setRevenue(Number(event.target.value))} /><span>€</span></div></label><label>EBITDA<div className="suffix-input"><input type="number" value={ebitda} onChange={(event) => setEbitda(Number(event.target.value))} /><span>€</span></div></label><label>Multiple<div className="suffix-input"><input type="number" step="0.1" value={multiple} onChange={(event) => setMultiple(Number(event.target.value))} /><span>×</span></div></label><label>Dette nette brute<div className="suffix-input"><input type="number" value={debt} onChange={(event) => setDebt(Number(event.target.value))} /><span>€</span></div></label><label>Cash<div className="suffix-input"><input type="number" value={cash} onChange={(event) => setCash(Number(event.target.value))} /><span>€</span></div></label><label>Participation<div className="suffix-input"><input type="number" min="0" max="100" value={ownership} onChange={(event) => setOwnership(Number(event.target.value))} /><span>%</span></div></label></div></article><div className="results-stack"><section className="metrics-grid two"><MetricCard label="Valeur d’entreprise" value={<Currency value={enterpriseValue} />} /><MetricCard label="Equity value" value={<Currency value={equityValue} />} /><MetricCard label="Valeur attribuable" value={<Currency value={attributable} />} tone="positive" /><MetricCard label="Marge EBITDA" value={<Percent value={revenue === 0 ? 0 : ebitda / revenue} />} /></section><article className="panel org-chart"><div className="panel-header"><div><span className="eyebrow">Organigramme patrimonial</span><h2>Structure testée</h2></div></div><div className="org-tree"><div className="org-person">Léo<br /><small>{ownership} %</small></div><span className="org-line" /><div className="org-company">Société cible<br /><small>Valeur attribuable <Currency value={attributable} /></small></div></div></article></div></section>
  </div>;
}

function TaxPage({ state }: SectionProps) {
  return <div className="page-stack"><SectionHeader eyebrow="Tax architecture" title="Tax" description="Couche fiscale datée et paramétrable. Aucune règle non vérifiée n’est appliquée comme vérité." />
    <Callout tone="warning" title="Pas de conseil fiscal">La V1 n’émet pas de conseil juridique ou fiscal. Les paramètres 2026 doivent être vérifiés à partir de sources officielles avant tout calcul décisionnel.</Callout>
    <section className="metrics-grid four"><MetricCard label="Résidence fiscale" value="France" detail="Profil individuel" /><MetricCard label="Foyer" value="Individuel" detail="Compagne exclue du patrimoine" /><MetricCard label="Règles actives vérifiées" value="0" tone="warning" detail="Architecture prête" /><MetricCard label="Année de référence" value="2026" detail="À sourcer" /></section>
    <section className="two-column"><article className="panel"><div className="panel-header"><div><span className="eyebrow">Enveloppes</span><h2>Traitements prévus</h2></div></div><div className="feature-list">{["Impôt sur le revenu français", "Prélèvements sociaux", "PEA", "CTO", "Assurance-vie", "Immobilier", "Dividendes & plus-values", "Business equity"].map((item) => <div key={item}><ReceiptText size={15} /><span>{item}</span><span className="status-outline">Paramétrable</span></div>)}</div></article><article className="panel"><div className="panel-header"><div><span className="eyebrow">Gouvernance</span><h2>Règle fiscale</h2></div></div><div className="governance-list"><div><span>Année applicable</span><strong>Obligatoire</strong></div><div><span>Source officielle</span><strong>Obligatoire</strong></div><div><span>Dernière vérification</span><strong>Obligatoire</strong></div><div><span>Modification utilisateur</span><strong>Historisée</strong></div><div><span>Confiance</span><strong>Visible</strong></div></div></article></section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Hypothèses fiscales</span><h2>Registre</h2></div></div>{state.assumptions.filter((assumption) => assumption.id === "asm_tax").map((assumption) => <div className="assumption-row" key={assumption.id}><div><strong>{assumption.name}</strong><span>{String(assumption.value)}</span></div><DataBadge kind={assumption.provenance.kind} /><span className="confidence low">Confiance faible</span></div>)}</section>
  </div>;
}

function ScenariosPage({ state, mutate, busy, projection, runProjection, setExplanation }: SectionProps) {
  const [selectedId, setSelectedId] = useState(state.scenarios.find((scenario) => scenario.name === "Central")?.id ?? state.scenarios[0].id);
  const [editing, setEditing] = useState<Scenario | null>(null);
  const [form, setForm] = useState({ annualReturn: "", annualVolatility: "", annualInflation: "", monthlySavings: "", salaryGrowth: "", stressProbability: "", shockYear: "", shockMagnitude: "" });
  const [seed, setSeed] = useState(19082026);
  function editScenario(scenario: Scenario) { setEditing(scenario); setForm({ annualReturn: String(scenario.annualReturn * 100), annualVolatility: String(scenario.annualVolatility * 100), annualInflation: String(scenario.annualInflation * 100), monthlySavings: String(scenario.monthlySavings), salaryGrowth: String(scenario.salaryGrowth * 100), stressProbability: String(scenario.stressProbability * 100), shockYear: scenario.shockYear === null ? "" : String(scenario.shockYear), shockMagnitude: scenario.shockMagnitude === null ? "" : String(scenario.shockMagnitude * 100) }); }
  async function saveScenario(event: React.FormEvent) { event.preventDefault(); if (!editing) return; const ok = await mutate({ action: "update_scenario", scenarioId: editing.id, patch: { annualReturn: inputNumber(form.annualReturn) / 100, annualVolatility: inputNumber(form.annualVolatility) / 100, annualInflation: inputNumber(form.annualInflation) / 100, monthlySavings: inputNumber(form.monthlySavings), salaryGrowth: inputNumber(form.salaryGrowth) / 100, stressProbability: inputNumber(form.stressProbability) / 100, shockYear: form.shockYear ? inputNumber(form.shockYear) : null, shockMagnitude: form.shockMagnitude ? inputNumber(form.shockMagnitude) / 100 : null } }); if (ok) setEditing(null); }
  const finalPoint = projection?.points.at(-1);
  return <div className="page-stack"><SectionHeader eyebrow="Scenario engine" title="Scenarios" description="Les scénarios remplacent uniquement les hypothèses futures. Ils ne modifient jamais l’historique ACTUAL." actions={<button className="button secondary" onClick={() => mutate({ action: "duplicate_scenario", scenarioId: selectedId })}><Copy size={15} />Dupliquer</button>} />
    <div className="scenario-grid">{state.scenarios.map((scenario) => <article key={scenario.id} className={`scenario-card ${selectedId === scenario.id ? "selected" : ""}`} onClick={() => setSelectedId(scenario.id)}><div className="scenario-top"><span className="scenario-color" style={{ background: scenario.color }} /><span><strong>{scenario.name}</strong><small>Version {scenario.version}</small></span><DataBadge kind={scenario.provenance.kind} /></div><p>{scenario.description}</p><div className="scenario-stats"><div><span>Rendement</span><strong><Percent value={scenario.annualReturn} /></strong></div><div><span>Volatilité</span><strong><Percent value={scenario.annualVolatility} /></strong></div><div><span>Épargne</span><strong><Currency value={scenario.monthlySavings} /></strong></div></div><button className="link-button" onClick={(event) => { event.stopPropagation(); editScenario(scenario); }}>Modifier les hypothèses</button></article>)}</div>
    <section className="panel simulation-panel"><div className="panel-header"><div><span className="eyebrow">Monte-Carlo</span><h2>Distribution projetée</h2></div><div className="simulation-actions"><label>Seed<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label><button className="button primary" disabled={busy} onClick={() => runProjection(selectedId, 30, 3000, seed)}><Sparkles size={15} />Lancer 3 000 simulations</button></div></div>{projection ? <><div className="simulation-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={projection.points}><defs><linearGradient id="band90" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#39747a" stopOpacity={0.2} /><stop offset="1" stopColor="#39747a" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border-soft)" /><XAxis dataKey="year" axisLine={false} tickLine={false} /><YAxis tickFormatter={chartCurrency} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(Number(value))} /><Area type="monotone" dataKey="p90" stackId="band" stroke="none" fill="url(#band90)" name="P90" /><Area type="monotone" dataKey="p10" stroke="#9b8555" fill="transparent" strokeDasharray="3 3" name="P10" /><Line type="monotone" dataKey="p50" stroke="#2f6c72" strokeWidth={2.4} dot={false} name="P50" /></AreaChart></ResponsiveContainer></div><div className="percentile-cards"><div><span>P10</span><strong><Currency value={finalPoint?.p10 ?? 0} compact /></strong><small>Dépassé favorablement dans ~90 % des simulations du modèle</small></div><div><span>P50</span><strong><Currency value={finalPoint?.p50 ?? 0} compact /></strong><small>Médiane des simulations</small></div><div><span>P90</span><strong><Currency value={finalPoint?.p90 ?? 0} compact /></strong><small>Atteint ou dépassé dans ~10 % des simulations du modèle</small></div></div><button className="link-button explain-link" onClick={() => setExplanation({ title: "Monte-Carlo", formula: "Aₜ₊₁ = max(0, Aₜ × (1 + rₜ) + épargne mensuelle)", inputs: [{ label: "Simulations", value: String(projection.simulations), kind: "MODEL_ASSUMPTION" }, { label: "Seed", value: String(projection.seed), kind: "MODEL_ASSUMPTION" }, { label: "Scénario", value: state.scenarios.find((scenario) => scenario.id === projection.scenarioId)?.name ?? projection.scenarioId, kind: "USER_ASSUMPTION" }], note: projection.methodology })}>Explain calculation</button></> : <EmptyState title="Projection non lancée" detail="Le moteur utilise des rendements mensuels à queues épaisses, des stress rares et un seed reproductible." action={<button className="button primary" onClick={() => runProjection(selectedId, 30, 3000, seed)}>Lancer la projection</button>} />}</section>
    <Modal open={Boolean(editing)} onClose={() => setEditing(null)} title={`Modifier ${editing?.name ?? "le scénario"}`} subtitle="Une nouvelle version est créée à chaque sauvegarde"><form className="form-grid" onSubmit={saveScenario}><label>Rendement annuel<input className="text-input" type="number" step="0.1" value={form.annualReturn} onChange={(event) => setForm({ ...form, annualReturn: event.target.value })} /></label><label>Volatilité annuelle<input className="text-input" type="number" step="0.1" value={form.annualVolatility} onChange={(event) => setForm({ ...form, annualVolatility: event.target.value })} /></label><label>Inflation<input className="text-input" type="number" step="0.1" value={form.annualInflation} onChange={(event) => setForm({ ...form, annualInflation: event.target.value })} /></label><label>Épargne mensuelle<input className="text-input" type="number" value={form.monthlySavings} onChange={(event) => setForm({ ...form, monthlySavings: event.target.value })} /></label><label>Croissance salaire<input className="text-input" type="number" step="0.1" value={form.salaryGrowth} onChange={(event) => setForm({ ...form, salaryGrowth: event.target.value })} /></label><label>Probabilité stress annuelle<input className="text-input" type="number" step="0.1" value={form.stressProbability} onChange={(event) => setForm({ ...form, stressProbability: event.target.value })} /></label><label>Année du choc<input className="text-input" type="number" placeholder="Aucun" value={form.shockYear} onChange={(event) => setForm({ ...form, shockYear: event.target.value })} /></label><label>Magnitude du choc (%)<input className="text-input" type="number" placeholder="Aucune" value={form.shockMagnitude} onChange={(event) => setForm({ ...form, shockMagnitude: event.target.value })} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setEditing(null)}>Annuler</button><button className="button primary" disabled={busy}><Save size={15} />Créer la version {editing ? editing.version + 1 : ""}</button></div></form></Modal>
  </div>;
}

function DecisionLabPage({ state }: SectionProps) {
  const [cash, setCash] = useState(5000); const [returnRate, setReturnRate] = useState(5.5); const [volatility, setVolatility] = useState(15); const [years, setYears] = useState(5);
  const result = compareDebtVsInvest({ availableCash: cash, debtBalance: state.metrics.debt, debtRate: 0, investmentReturn: returnRate / 100, volatility: volatility / 100, inflation: 0.02, years, liquidityWeight: 0.03 });
  const cases = ["Louer vs acheter", "RP vs locatif", "Paris vs autre zone", "Immobilier vs bourse", "Rembourser vs investir", "PEA vs CTO vs assurance-vie", "Apport faible vs élevé", "M&A vs PE", "Salariat vs entrepreneuriat", "Cash vs investir"];
  return <div className="page-stack"><SectionHeader eyebrow="Decision framework" title="Decision Lab" description="Comparer le rendement, mais aussi liquidité, risque, flexibilité et coût d’opportunité." />
    <section className="decision-case-strip">{cases.map((item) => <button key={item} className={item === "Rembourser vs investir" ? "active" : ""}>{item}{item !== "Rembourser vs investir" ? <span>Préparé</span> : <Check size={13} />}</button>)}</section>
    <section className="decision-workbench"><article className="panel input-panel"><div className="panel-header"><div><span className="eyebrow">Cas actif</span><h2>Rembourser vs investir</h2></div></div><div className="decision-slider-list"><label><span>Capital disponible<strong><Currency value={cash} /></strong></span><input type="range" min="500" max="16745" step="250" value={cash} onChange={(event) => setCash(Number(event.target.value))} /></label><label><span>Rendement espéré<strong>{returnRate.toFixed(1)} %</strong></span><input type="range" min="0" max="12" step="0.1" value={returnRate} onChange={(event) => setReturnRate(Number(event.target.value))} /></label><label><span>Volatilité<strong>{volatility} %</strong></span><input type="range" min="0" max="35" step="1" value={volatility} onChange={(event) => setVolatility(Number(event.target.value))} /></label><label><span>Horizon<strong>{years} ans</strong></span><input type="range" min="1" max="15" value={years} onChange={(event) => setYears(Number(event.target.value))} /></label></div><DataBadge kind="USER_ASSUMPTION" /></article><div className="decision-results"><div className="option-card"><span className="option-icon"><Landmark size={20} /></span><span className="eyebrow">Option A</span><h2>Rembourser</h2><strong className="option-value"><Currency value={result.repay.nominalBenefit} /></strong><small>Valeur nominale équivalente</small><dl><div><dt>Gain certain</dt><dd>0 €</dd></div><div><dt>Liquidité</dt><dd>Très faible</dd></div><div><dt>Risque</dt><dd>Faible</dd></div><div><dt>Flexibilité</dt><dd>Faible</dd></div></dl></div><div className="option-card preferred"><span className="recommended">Espérance ajustée supérieure</span><span className="option-icon"><TrendingUp size={20} /></span><span className="eyebrow">Option B</span><h2>Investir</h2><strong className="option-value"><Currency value={result.invest.nominalBenefit} /></strong><small>Valeur espérée non garantie</small><dl><div><dt>Avantage ajusté</dt><dd><Currency value={result.opportunityAdvantage} sign /></dd></div><div><dt>Liquidité</dt><dd>Modérée</dd></div><div><dt>Risque</dt><dd>{result.invest.risk}</dd></div><div><dt>Flexibilité</dt><dd>Élevée</dd></div></dl></div></div></section>
    <Callout title="Conclusion multicritère">{result.conclusion} Avec seulement <Currency value={state.metrics.bankCash} /> de cash bancaire, la réserve de sécurité prévaut avant l’une ou l’autre option.</Callout>
  </div>;
}

function GoalsPage({ state, mutate, busy }: SectionProps) {
  const [modal, setModal] = useState(false); const [form, setForm] = useState({ name: "", target: "100000", date: "" });
  async function add(event: React.FormEvent) { event.preventDefault(); const ok = await mutate({ action: "add_goal", name: form.name, targetAmount: inputNumber(form.target), targetDate: form.date || null }); if (ok) { setModal(false); setForm({ name: "", target: "100000", date: "" }); } }
  const milestones = [100000, 250000, 500000, 1000000, 2000000, 5000000, 10000000, 20000000];
  return <div className="page-stack"><SectionHeader eyebrow="Milestones" title="Goals" description="Les seuils sont des repères, pas la fonction objectif du moteur de décision." actions={<button className="button primary" onClick={() => setModal(true)}><Plus size={16} />Nouvel objectif</button>} />
    <section className="goals-grid">{state.goals.map((goal) => { const progress = Math.max(0, state.metrics.netWorth) / goal.targetAmount; return <article className="panel goal-card-large" key={goal.id}><div className="goal-icon"><Target size={19} /></div><DataBadge kind="USER_ASSUMPTION" /><h2>{goal.name}</h2><div className="goal-big"><Currency value={Math.max(0, state.metrics.netWorth)} /><span>/ <Currency value={goal.targetAmount} /></span></div><ProgressBar value={progress} tone={goal.priority === 1 ? "teal" : "gold"} /><div className="goal-foot"><span>{Math.round(progress * 100)} % atteint</span><span>{goal.targetDate ? `Cible ${new Date(goal.targetDate).getFullYear()}` : "Sans date"}</span></div></article>; })}</section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Repères configurables</span><h2>Milestones patrimoniaux</h2></div></div><div className="milestone-line">{milestones.map((milestone) => <div key={milestone} className={state.metrics.netWorth >= milestone ? "achieved" : ""}><i /><strong><Currency value={milestone} compact /></strong></div>)}</div></section>
    <section className="metrics-grid four"><MetricCard label="FI ratio" value="Non calculable" detail="Dépenses souhaitées manquantes" tone="warning" /><MetricCard label="Freedom Coverage" value="Non calculable" detail="Revenus passifs = 0" /><MetricCard label="Coast FIRE" value="Secondaire" detail="Objectif non prioritaire" /><MetricCard label="Premier objectif" value="Retour à 0 €" detail="Patrimoine net identifié" /></section>
    <Modal open={modal} onClose={() => setModal(false)} title="Nouvel objectif" subtitle="Un objectif peut être financier, de liquidité ou de liberté"><form className="form-grid" onSubmit={add}><label className="full">Nom<input className="text-input" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Montant cible<input className="text-input" type="number" min="1" value={form.target} onChange={(event) => setForm({ ...form, target: event.target.value })} required /></label><label>Date cible (optionnelle)<input className="text-input" type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><div className="form-actions"><button type="button" className="button secondary" onClick={() => setModal(false)}>Annuler</button><button className="button primary" disabled={busy}>Créer</button></div></form></Modal>
  </div>;
}

function DocumentsPage({ state, refresh }: SectionProps) {
  const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setUploading(true); setError(""); const body = new FormData(event.currentTarget); const response = await fetch("/api/documents", { method: "POST", body }); const payload = await response.json().catch(() => ({})); if (!response.ok) setError(payload.error ?? "Import impossible"); else { event.currentTarget.reset(); await refresh(); } setUploading(false); }
  const categories = ["bank", "investment", "tax", "real_estate", "business", "employment", "loan", "insurance", "other"];
  return <div className="page-stack"><SectionHeader eyebrow="Private vault" title="Documents" description="Coffre local privé. Les fichiers ne sont jamais publics et aucun identifiant bancaire n’est accepté." />
    <section className="document-layout"><form className="panel upload-panel" onSubmit={upload}><span className="upload-icon"><UploadCloud size={24} /></span><h2>Déposer un document</h2><p>PDF, PNG, JPG, CSV ou XLSX · 8 Mo maximum</p><input id="document-file" type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.csv,.xlsx" required /><label htmlFor="document-file" className="button primary">Choisir un fichier</label><select className="text-input" name="category" defaultValue="other">{categories.map((category) => <option key={category} value={category}>{category.replace("_", " ")}</option>)}</select><button className="button secondary" disabled={uploading}>{uploading ? "Import…" : "Ajouter à l’inbox"}</button>{error ? <div className="form-error">{error}</div> : null}<small><LockKeyhole size={13} />Stockage local privé dans cette V1</small></form><article className="panel"><div className="panel-header"><div><span className="eyebrow">Inbox</span><h2>Documents non classés</h2></div><span className="nav-count">{state.documents.filter((document) => document.status === "INBOX").length}</span></div>{state.documents.length ? <div className="document-list">{state.documents.map((document) => <div key={document.id}><span className="document-icon"><FileText size={17} /></span><span><strong>{document.name}</strong><small>{document.category} · {(document.size / 1024).toFixed(1)} Ko · {new Date(document.uploadedAt).toLocaleDateString("fr-FR")}</small></span><span className="status-outline">Inbox</span></div>)}</div> : <EmptyState title="Coffre vide" detail="Le premier fichier importé apparaîtra ici, sans analyse automatique en V1." />}</article></section>
    <section className="category-cards">{categories.map((category) => <div key={category}><FolderOpen size={17} /><span>{category.replace("_", " ")}</span><strong>{state.documents.filter((document) => document.category === category).length}</strong></div>)}</section>
  </div>;
}

function TimelinePage({ state, mutate, busy }: SectionProps) {
  const events = [
    { date: "19 août 2026", kind: "Actual", title: "Date zéro", detail: `Patrimoine net identifié ${new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.netWorth)}`, tone: "actual" },
    { date: "5 décembre 2026", kind: "Contractuel", title: "Première échéance étudiant", detail: "284,72 € annoncés", tone: "warning" },
    { date: "2027", kind: "Hypothèse", title: "Premier CDI principal", detail: "40–45 k€ fixe brut + variable", tone: "model" },
    { date: "~ 2029", kind: "Scénario", title: "Tentative de passage M&A → PE", detail: "Après environ deux ans, sans certitude", tone: "model" },
    { date: "5 novembre 2031", kind: "Prévision", title: "Dernière échéance étudiant", detail: "Sous réserve de l’échéancier réel", tone: "warning" },
  ];
  return <div className="page-stack"><SectionHeader eyebrow="History & future" title="Timeline" description="Clôtures mensuelles observées et événements futurs clairement distingués." actions={<button className="button primary" disabled={busy} onClick={() => mutate({ action: "create_monthly_close", closeDate: state.asOfDate })}><CalendarCheck size={15} />Clôturer août 2026</button>} />
    <section className="timeline-layout"><article className="panel"><div className="panel-header"><div><span className="eyebrow">Événements</span><h2>Trajectoire patrimoniale</h2></div></div><div className="full-timeline">{events.map((event) => <div key={event.title} className={event.tone}><div className="timeline-date">{event.date}</div><i /><div><span>{event.kind}</span><h3>{event.title}</h3><p>{event.detail}</p></div></div>)}</div></article><aside className="results-stack"><article className="panel"><div className="panel-header"><div><span className="eyebrow">Monthly close</span><h2>Clôtures figées</h2></div></div>{state.monthlyCloses.length ? <div className="close-list">{state.monthlyCloses.map((close) => <div key={close.id}><span><strong>{new Date(close.closeDate).toLocaleDateString("fr-FR", { month: "long", year: "numeric" })}</strong><small>Snapshot actual</small></span><strong><Currency value={close.netWorth} /></strong></div>)}</div> : <EmptyState title="Aucune clôture" detail="Clôturer août figera soldes, positions, dette et patrimoine net." />}</article><Callout title="Écart réel vs prévu">À partir de la deuxième clôture, le cockpit conservera l’écart avec la prévision précédente.</Callout></aside></section>
  </div>;
}

function SettingsPage({ state }: SectionProps) {
  return <div className="page-stack"><SectionHeader eyebrow="Governance" title="Settings & Assumptions" description="Registre des hypothèses, provenance, confiance, sécurité et portabilité." actions={<a className="button secondary" href="/api/export?format=json"><Download size={15} />Backup JSON</a>} />
    <section className="metrics-grid four"><MetricCard label="Date zéro" value="19 août 2026" /><MetricCard label="Devise reporting" value={state.reportingCurrency} detail="Multi-devises prêt" /><MetricCard label="Adapter actif" value="SQLite local" detail="Supabase prêt à connecter" /><MetricCard label="Données externes actives" value="0" detail="Fallback manuel" /></section>
    <section className="panel"><div className="panel-header"><div><span className="eyebrow">Assumption register</span><h2>Hypothèses importantes</h2></div></div><div className="assumption-table"><div className="table-head"><span>Hypothèse</span><span>Valeur</span><span>Unité</span><span>Provenance</span><span>Confiance</span></div>{state.assumptions.map((assumption) => <div className="table-row" key={assumption.id}><span><strong>{assumption.name}</strong><small>{assumption.provenance.notes ?? assumption.provenance.source}</small></span><strong>{typeof assumption.value === "number" && assumption.unit.includes("EUR") ? <Currency value={assumption.value} /> : String(assumption.value ?? "—")}</strong><span>{assumption.unit}</span><DataBadge kind={assumption.provenance.kind} /><span className={`confidence ${assumption.provenance.confidence.toLowerCase()}`}>{assumption.provenance.confidence}</span></div>)}</div></section>
    <section className="two-column"><article className="panel"><div className="panel-header"><div><span className="eyebrow">Security</span><h2>Statut V1</h2></div><ShieldAlert size={18} /></div><div className="security-checklist"><div className="ok"><Check size={14} /><span>Routes protégées par session HttpOnly</span></div><div className="ok"><Check size={14} /><span>Validation stricte des inputs</span></div><div className="ok"><Check size={14} /><span>Aucun secret dans le frontend</span></div><div className="ok"><Check size={14} /><span>Fichiers privés et types limités</span></div><div className="ok"><Check size={14} /><span>Aucune écriture bancaire ou courtier</span></div><div className="pending"><AlertTriangle size={14} /><span>Déployer Supabase Auth + RLS avant exposition internet</span></div></div></article><article className="panel"><div className="panel-header"><div><span className="eyebrow">Exports</span><h2>Portabilité des données</h2></div></div><div className="export-list"><a href="/api/export?format=csv"><FileArchive size={18} /><span><strong>Balance sheet CSV</strong><small>Comptes et dettes consolidés</small></span><Download size={15} /></a><a href="/api/export?format=json"><FileText size={18} /><span><strong>Backup complet JSON</strong><small>Données, hypothèses et scénarios</small></span><Download size={15} /></a><button><BadgeEuro size={18} /><span><strong>Rapport patrimonial PDF</strong><small>Préparé pour V1.1</small></span><span className="soon">Coming soon</span></button><button><FileText size={18} /><span><strong>Investment Committee Memo</strong><small>Préparé pour V1.1</small></span><span className="soon">Coming soon</span></button></div></article></section>
  </div>;
}

function assetsExplanation(state: DashboardState): Explanation { return { title: "Actifs bruts identifiés", formula: "Σ dernier solde de chaque compte actif", inputs: state.accounts.map((account) => ({ label: account.name, value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(account.balance), kind: account.provenance.kind, date: account.balanceDate, source: account.provenance.source })), note: "Les positions PEA et CTO ne sont pas ajoutées : elles expliquent le solde du compte et évitent le double comptage." }; }
function netWorthExplanation(state: DashboardState): Explanation { return { title: "Patrimoine net identifié", formula: "Actifs bruts identifiés − dettes identifiées", inputs: [{ label: "Actifs bruts", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.grossAssets), kind: "DERIVED", date: state.asOfDate }, { label: "Dette étudiante", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.debt), kind: "ACTUAL", date: state.asOfDate, source: "Donnée communiquée par Léo" }], note: "Ce chiffre vaut −1 173,51 € à la date zéro et reste un patrimoine net identifié, non exhaustif." }; }
function liquidityExplanation(state: DashboardState): Explanation { return { title: "Couverture de liquidité", formula: "Cash bancaire immédiat ÷ dépenses essentielles mensuelles connues", inputs: [{ label: "Cash bancaire", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.bankCash), kind: "DERIVED", date: state.asOfDate }, { label: "Dépenses essentielles connues", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.monthlyExpenses), kind: "ACTUAL", date: state.asOfDate }], note: "Seul le loyer est renseigné : la couverture réelle est probablement inférieure. Le cash PEA est exclu du cash bancaire disponible." }; }
function cashFlowExplanation(state: DashboardState): Explanation { return { title: "Cash flow mensuel connu", formula: "Revenus actifs − dépenses renseignées − service de dette exigible à la date zéro", inputs: [{ label: "Revenu net actuel", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.monthlyIncome), kind: "ACTUAL", date: state.asOfDate }, { label: "Dépenses connues", value: new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(state.metrics.monthlyExpenses), kind: "ACTUAL", date: state.asOfDate }, { label: "Service de dette actuel", value: "0,00 € avant le 5 décembre 2026", kind: "DERIVED", date: state.asOfDate }], note: "La majorité des dépenses n’est pas encore renseignée. Ce cash flow ne doit pas être lu comme une capacité d’épargne définitive." }; }
